"use strict";

// Every Trainer and Energy card's name, from the Pokémon TCG API (pokemontcg.io), September 2026:
// 1363 Trainer names and 117 Energy names. The reader checks what it read against these as well as
// against the Pokémon names, so "Devolutlon Spray" becomes "Devolution Spray". Printed as on the
// card: the database's extras in brackets, like "(Professor Magnolia)", are left out.
// When new sets come out, add their new names.

const TRAINER_NAMES = [
	"AZ", "AZ's Tranquility", "Aaron's Collection", "Academy at Night", "Accompanying Flute",
	"Ace Trainer", "Acerola", "Acerola's Mischief", "Acerola's Premonition", "Acro Bike", "Adaman",
	"Adventure Bag", "Adventurer's Discovery", "Adversity Policy", "Aerodactyl Spirit Link",
	"Aether Foundation Employee", "Aether Paradise Conservation Area", "Agatha", "Aggron Spirit Link",
	"Air Balloon", "Alakazam Spirit Link", "All-Night Party", "Allister", "Alph Lithograph",
	"Altar of the Moone", "Altar of the Sunne", "Altaria Spirit Link", "Amarys",
	"Ampharos Spirit Link", "Amulet Coin", "Amulet of Hope", "Ancient Booster Energy Capsule",
	"Ancient Crystal", "Ancient Ruins", "Ancient Technical Machine", "Ancient Tomb", "Ange Floette",
	"Anthea & Concordia", "Antique Armor Fossil", "Antique Cover Fossil", "Antique Dome Fossil",
	"Antique Helix Fossil", "Antique Jaw Fossil", "Antique Old Amber", "Antique Plume Fossil",
	"Antique Root Fossil", "Antique Sail Fossil", "Antique Skull Fossil", "Apricorn Forest",
	"Apricorn Maker", "Aqua Diffuser", "Aqua Patch", "Arc Phone", "Arcade Game", "Archie",
	"Archie's Ace in the Hole", "Area Zero Underdepths", "Arezu", "Armor Fossil",
	"Armor Fossil Shieldon", "Aroma Lady", "Artazon", "Arven", "Arven's Sandwich",
	"Aspertia City Gym", "Assault Vest", "Atticus", "Audino Spirit Link", "Avery", "Awakening Drum",
	"Babiri Berry", "Backtrack Badge", "Ball Guy", "Balloon Berry", "Barry", "Battle Cage",
	"Battle City", "Battle Compressor Team Flare Gear", "Battle Frontier", "Battle Reporter",
	"Battle Tower", "Battle VIP Pass", "Bea", "Beach Court", "Beast Ball", "Beast Bringer",
	"Beast Ring", "Beastite", "Beauty", "Bebe's Search", "Bede", "Beedrill Spirit Link",
	"Beginning Door", "Bellelba & Brycen-Man", "Bench Shield", "Bent Spoon", "Berry",
	"Bertha's Warmth", "Bianca", "Bianca's Devotion", "Bicycle", "Big Air Balloon", "Big Charm",
	"Big Malasada", "Big Parasol", "Bill", "Bill's Analysis", "Bill's Maintenance",
	"Bill's Teleporter", "Bill's Transfer", "Billowing Smoke", "Billy & O'Nare", "Binding Mochi",
	"Bird Keeper", "Black Belt", "Black Belt's Training", "Black Market", "Blacksmith", "Blaine",
	"Blaine's Gamble", "Blaine's Last Resort", "Blaine's Last Stand", "Blaine's Quiz",
	"Blaine's Quiz Show", "Blanche", "Blastoise Spirit Link", "Blizzard Town", "Blowtorch",
	"Blue's Tactics", "Blunder Policy", "Bodybuilding Dumbbells", "Bonnie", "Boost Shake",
	"Boss's Orders", "Box of Disaster", "Boxed Order", "Brandon", "Brassius", "Brave Bangle",
	"Bravery Charm", "Brawly", "Briar", "Brigette", "Brilliant Blender", "Brock", "Brock's Grit",
	"Brock's Pewter City Gym", "Brock's Protection", "Brock's Scouting", "Brock's Training",
	"Brock's Training Method", "Broken Ground Gym", "Broken Time-Space", "Brooklet Hill", "Bruno",
	"Bubble Coat", "Buck's Training", "Buddy-Buddy Poffin", "Buddy-Buddy Rescue", "Buff Padding",
	"Buffer Piece", "Bug Catcher", "Bug Catching Set", "Burned Tower", "Burning Scarf",
	"Bursting Balloon", "Café Master", "Caitlin", "Calamitous Snowy Mountain", "Calamitous Wasteland",
	"Call Bell", "Camerupt Spirit Link", "Camping Gear", "Canari", "Canceling Cologne", "Candela",
	"Candice", "Capacious Bucket", "Cape of Toughness", "Captivating Poké Puff", "Capturing Aroma",
	"Cara Liss", "Card-Flip Game", "Caretaker", "Carmine", "Cassiopeia", "Cassius", "Castaway",
	"Cedric Juniper", "Celadon City Gym", "Celio's Network", "Cerulean City Gym", "Cessation Crystal",
	"Challenge!", "Champion's Room", "Champions Festival", "Championship Arena", "Channeler",
	"Chaos Gym", "Chaos Tower", "Chaotic Swell", "Charity", "Charizard Spirit Link",
	"Charon's Choice", "Cheerleader's Cheer", "Cheren", "Cheren's Care", "Cherish Ball", "Cheryl",
	"Chili & Cilan & Cress", "Chill Teaser Toy", "Chip-Chip Ice Axe", "Choice Band", "Choice Belt",
	"Choice Helmet", "Choy", "Cilan", "Cinnabar City Gym", "Ciphermaniac's Codebreaking",
	"Circhester Bath", "Clavell", "Claw Fossil", "Claw Fossil Anorith", "Clay", "Cleansing Gloves",
	"Clefairy Doll", "Clemont", "Clemont's Quick Wit", "Clive", "Coach Trainer", "Colbur Berry",
	"Collapsed Stadium", "Colress", "Colress Machine", "Colress's Experiment", "Colress's Tenacity",
	"Community Center", "Computer Error", "Computer Search", "Conductive Quarry", "Cook", "Copycat",
	"Core Memory", "Counter Catcher", "Counter Gain", "Counterattack Claws", "Cover Fossil",
	"Cram-o-matic", "Crasher Wake", "Crispin", "Cross Switcher", "Crossceiver", "Crushing Gloves",
	"Crushing Hammer", "Crystal Beach", "Crystal Cave", "Crystal Edge", "Crystal Shard",
	"Crystal Wall", "Curse Powder", "Cursed Duster", "Cursed Shovel", "Cursed Stone",
	"Custom Catcher", "Cycling Road", "Cyllene", "Cynthia", "Cynthia & Caitlin", "Cynthia's Ambition",
	"Cynthia's Feelings", "Cynthia's Guidance", "Cynthia's Power Weight", "Cyrano", "Cyrus",
	"Cyrus's Conspiracy", "Cyrus's Initiative", "Daisy's Help", "Damage Mover", "Damage Pump", "Dan",
	"Dana", "Dancer", "Dangerous Drill", "Dangerous Laser", "Dark Bell", "Dark City", "Dark Claw",
	"Dark Patch", "Darkness Cube 01", "Dashing Pouch", "Dawn", "Dawn Stadium", "Deduction Kit",
	"Defender", "Defiance Band", "Defiance Vest", "Delinquent", "Delivery Drone", "Deluxe Bomb",
	"Dendra", "Department Store Girl", "Desert Ruins", "Desert Shaman", "Devolution Spray",
	"Devolution Spray Z", "Devoured Field", "Diantha", "Digger", "Digging Duo", "Digging Gloves",
	"Dimension Valley", "Dive Ball", "Dizzying Valley", "Doctor", "Dome Fossil", "Dome Fossil Kabuto",
	"Double Full Heal", "Double Gust", "Dowsing Machine", "Dragon Elixir", "Dragon Talon",
	"Dragonium Z: Dragon Claw", "Drake's Stadium", "Drasna", "Drayton", "Dream Ball", "Drone Rotom",
	"Dual Ball", "Dusk Ball", "Dusk Stone", "Dust Island", "Dyna Tree Hill", "EXP.ALL",
	"Ear-Ringing Bell", "Earthen Seal Stone", "Earthen Vessel", "Echoing Horn", "Eco Arm", "Ecogym",
	"Egg Incubator", "Electric Generator", "Electric Memory", "Electrocharger",
	"Electromagnetic Radar", "Electropower", "Elemental Badge", "Elesa", "Elesa's Sparkle",
	"Emcee's Chatter", "Emcee's Hype", "Emergency Jelly", "Emma", "Eneporter", "Energy Amplifier",
	"Energy Ark", "Energy Charge", "Energy Coin", "Energy Exchanger", "Energy Flow", "Energy Link",
	"Energy Loto", "Energy Pickup", "Energy Pouch", "Energy Recycle System", "Energy Recycler",
	"Energy Removal", "Energy Removal 2", "Energy Reset", "Energy Restore", "Energy Retrieval",
	"Energy Returner", "Energy Root", "Energy Search", "Energy Search Pro", "Energy Spinner",
	"Energy Stadium", "Energy Sticker", "Energy Swatter", "Energy Switch", "Engineer's Adjustments",
	"Enhanced Hammer", "Eri", "Erika", "Erika's Hospitality", "Erika's Invitation",
	"Erika's Jigglypuff", "Erika's Kindness", "Erika's Maids", "Erika's Perfume", "Escape Board",
	"Escape Rope", "Ethan's Adventure", "Ether", "Evelyn", "Eviolite", "Evolution Incense", "Evosoda",
	"Exp. Share", "Expedition Uniform", "Expert Belt", "Explorer's Guidance", "Faba", "Faded Town",
	"Fairy Charm Ability", "Fairy Charm Dragon", "Fairy Charm Fighting", "Fairy Charm Grass",
	"Fairy Charm Lightning", "Fairy Charm Psychic", "Fairy Charm UB", "Fairy Drop", "Fairy Garden",
	"Falkner", "Familiar Bell", "Fan of Waves", "Fantina", "Farewell Bell", "Fast Ball",
	"Feather Ball", "Felicity's Drawing", "Fennel", "Fervor", "Festival Grounds", "Field Blower",
	"Fieldworker", "Fiery Flint", "Fiery Torch", "Fighting Au Lait", "Fighting Cube 01",
	"Fighting Fury Belt", "Fighting Gong", "Fighting Memory", "Fighting Stadium", "Fire Crystal",
	"Fire Cube 01", "Fire Memory", "Fire-Resistant Gloves", "Firebreather", "First Ticket",
	"Fisherman", "Flannery", "Flint's Willpower", "Float Stone", "Floral Crown", "Flower Shop Lady",
	"Fluffy Berry", "Flyinium Z: Air Slash", "Focus Band", "Focus Sash", "Fog Crystal",
	"Forest Guardian", "Forest Seal Stone", "Forest of Giant Plants", "Forest of Vitality",
	"Fossil Egg", "Fossil Excavation Kit", "Fossil Excavation Map", "Fossil Excavator",
	"Fossil Quarry", "Fossil Researcher", "Fresh Water Set", "Friend Ball", "Friends in Galar",
	"Friends in Hisui", "Friends in Paldea", "Friends in Sinnoh", "Frozen City", "Fuchsia City Gym",
	"Full Face Guard", "Full Flame", "Full Heal", "Full Metal Lab", "Furisode Girl",
	"Future Booster Energy Capsule", "G Booster", "G Scope", "Galactic HQ", "Galar Mine",
	"Galarian Chestplate", "Gallade Spirit Link", "Gambler", "Gapejaw Bog", "Garchomp Spirit Link",
	"Gardenia", "Gardenia's Vigor", "Gardevoir Spirit Link", "Geeta", "Gengar Spirit Link", "Ghetsis",
	"Giacomo", "Giant Bomb", "Giant Cape", "Giant Hearth", "Giant Stump", "Giovanni",
	"Giovanni's Charisma", "Giovanni's Exile", "Giovanni's Last Resort", "Giovanni's Scheme",
	"Glacia's Stadium", "Gladion", "Gladion's Final Battle", "Glalie Spirit Link", "Glass Trumpet",
	"Glimwood Tangle", "Gloria", "Gold Berry", "Gold Potion", "Good Manners", "Good Rod",
	"Goop Gas Attack", "Gordie", "Grabber", "Grand Tree", "Granite Cave", "Grant", "Grass Cube 01",
	"Grass Memory", "Gravity Gemstone", "Gravity Mountain", "Great Ball", "Great Catcher",
	"Great Haul Net", "Great Potion", "Greedy Dice", "Green's Exploration", "Grimsley",
	"Grimsley's Move", "Groudon Spirit Link", "Grusha", "Gust of Wind", "Gutsy Pickaxe", "Guzma",
	"Guzma & Hala", "Gwynn", "Gyarados Spirit Link", "Gym Badge", "Gym Trainer", "Haban Berry",
	"Hala", "Hand Scope", "Hand Trimmer", "Handheld Fan", "Hapu", "Hard Charm", "Harlequin", "Hassel",
	"Hau", "Head Ringer Team Flare Hyper Gear", "Heal Powder", "Healing Berry", "Healing Field",
	"Healing Scarf", "Heat Factory", "Heavy Ball", "Heavy Baton", "Heavy Boots", "Helix Fossil",
	"Helix Fossil Omanyte", "Here Comes Team Rocket!", "Hero's Cape", "Hero's Medal", "Hex Maniac",
	"High Pressure System", "Hiker", "Hilda", "Hisuian Heavy Ball", "Hole-Digging Shovel",
	"Holon Adventurer", "Holon Circle", "Holon Farmer", "Holon Fossil", "Holon Lake", "Holon Lass",
	"Holon Legacy", "Holon Mentor", "Holon Research Tower", "Holon Researcher", "Holon Ruins",
	"Holon Scientist", "Holon Transceiver", "Honey", "Hooligans Jim & Cas", "Hop", "Hop's Bag",
	"Hop's Choice Band", "Houndoom Spirit Link", "Hugh", "Hunting Gloves", "Hustle Belt",
	"Hyper Aroma", "Hyper Devolution Spray", "Hyper Potion", "Hypnotoxic Laser", "Ilima", "Imakuni?",
	"Imposter Oak's Revenge", "Imposter Professor Oak", "Impostor Professor Oak",
	"Impostor Professor Oak's Invention", "Indigo Plateau", "Ingo & Emmet", "Interviewer's Questions",
	"Iono", "Irida", "Iris", "Iris's Fighting Spirit", "Iron Defender", "Iscan", "Island Cave",
	"Island Challenge Amulet", "Island Hermit", "Item Finder", "Jacinthe", "Jacq",
	"Jamming Net Team Flare Hyper Gear", "Jamming Tower", "Janine", "Janine's Secret Art", "Jasmine",
	"Jasmine's Gaze", "Jaw Fossil", "Jessie & James", "Jett", "Jubilife Village", "Judge",
	"Judge Whistle", "Juggler", "Jumbo Ice Cream", "Junk Arm", "Justified Gloves", "Kabu", "Kahili",
	"Kamado", "Karate Belt", "Karen", "Karen's Conviction", "Katy", "Kiawe", "Kieran", "Kindler",
	"Klara", "Kofu", "Koga", "Koga's Ninja Trick", "Koga's Trap", "Korrina", "Korrina's Focus",
	"Kyogre Spirit Link", "Lacey", "Lady", "Lady Outing", "Lake Acuity", "Lake Boundary", "Lana",
	"Lana's Aid", "Lana's Fishing Rod", "Lance", "Lanette's Net Search", "Larry", "Larry's Skill",
	"Lass", "Lass's Special", "Last Chance Potion", "Latios Spirit Link", "Lavender Town",
	"Leafy Camo Poncho", "League Staff", "Leftovers", "Legend Box", "Leon", "Letter of Encouragement",
	"Level Ball", "Level Max", "Levincia", "Life Dew", "Life Forest", "Life Herb", "Light Ball",
	"Lightning Cube 01", "Lillie", "Lillie's Determination", "Lillie's Full Force", "Lillie's Pearl",
	"Lillie's Poké Doll", "Lisia", "Lisia's Appeal", "Lively Stadium", "Looker", "Looker Whistle",
	"Looker's Investigation", "Lost Blender", "Lost City", "Lost Remover", "Lost Vacuum",
	"Lost World", "Love Ball", "Low Pressure System", "Lt. Surge", "Lt. Surge's Bargain",
	"Lt. Surge's Secret Plan", "Lt. Surge's Strategy", "Lt. Surge's Treaty", "Lucario Spirit Link",
	"Lucian", "Lucian's Assignment", "Lucky Egg", "Lucky Helmet", "Lucky Ice Pop", "Lucky Stadium",
	"Lum Berry", "Lumiose City", "Lumiose Galette", "Lure Ball", "Lure Module", "Lusamine",
	"Luxurious Cape", "Luxury Ball", "Lysandre", "Lysandre Labs", "Lysandre's Trump Card",
	"Magma Basin", "Magma Pointer", "Magnetic Storm", "Magnifier", "Mail from Bill", "Maintenance",
	"Mallow", "Mallow & Lana", "Manectric Spirit Link", "Marley's Request", "Marnie",
	"Marnie's Pride", "Mars", "Martial Arts Dojo", "Mary", "Mary's Impulse", "Mary's Request",
	"Master Ball", "Mawile Spirit Link", "Max Elixir", "Max Potion", "Max Revive", "Max Rod", "Maxie",
	"Maxie's Hidden Ball Trick", "Maximum Belt", "Meddling Memo", "Mega Catcher", "Mega Signal",
	"Mega Turbo", "Megaton Blower", "Mela", "Melony", "Memory Berry", "Memory Capsule", "Mesagoza",
	"Metal Core Barrier", "Metal Cube 01", "Metal Frying Pan", "Metal Goggles", "Metal Saucer",
	"Meteor Falls", "Mewtwo Spirit Link", "Miasma Valley", "Milo", "Mina", "Minion of Team Rocket",
	"Miracle Berry", "Miracle Headset", "Miracle Sphere", "Mirage Gate", "Mirage Stadium", "Miriam",
	"Miss Fortune Sisters", "Missing Clover", "Misty", "Misty & Lorelei", "Misty's Cerulean City Gym",
	"Misty's Determination", "Misty's Duel", "Misty's Favor", "Misty's Tears", "Misty's Vitality",
	"Misty's Water Command", "Misty's Wish", "Misty's Wrath", "Mixed Herbs", "Molayne",
	"Mom's Kindness", "Moo-Moo Milk", "Moomoo Cheese", "Moomoo Milk", "Moon & Sun Badge",
	"Moonlight Stadium", "Moonlit Hill", "Morgan", "Morty", "Morty's Conviction", "Mount Lanakila",
	"Mountain Ring", "Mr. Briney's Compassion", "Mr. Fuji", "Mr. Stone's Project", "Mt. Coronet",
	"Mt. Moon", "Multi Switch", "Multi Technical Machine 01", "Muscle Band", "Mysterious Fossil",
	"Mysterious Shard", "Mysterious Treasure", "Mystery Garden", "Mystery Plate", "Mystery Zone", "N",
	"N's Castle", "N's PP Up", "N's Plan", "N's Resolve", "Nanu", "Narrow Gym", "Naveen", "Nemona",
	"Nemona's Backpack", "Nessa", "Nest Ball", "Net Ball", "Neutralization Zone", "New Pokédex",
	"Night Maintenance", "Night Pokémon Center", "Night Stretcher", "Night Teleporter",
	"Nightly Garbage Run", "Nighttime Mine", "Ninja Boy", "Nita", "No Removal Gym",
	"Normalium Z: Tackle", "Norman", "Nugget", "Occa Berry", "Ogre's Mask", "Old Amber",
	"Old Amber Aerodactyl", "Old Cemetery", "Old PC", "Old Rod", "Oleana", "Olivia", "Olympia",
	"Opal", "Oracle", "Oran Berry", "Order Pad", "Ordinary Rod", "Ortega", "Paint Roller", "Pal Pad",
	"Paldean Student", "Palmer's Contribution", "Panic Mask", "Paradise Resort", "Parallel City",
	"Parasol Lady", "Passho Berry", "Path to the Peak", "Patrol Cap", "Payapa Berry",
	"Peeking Red Card", "Penny", "Peonia", "Peony", "Perilous Jungle", "Perrin", "Pewter City Gym",
	"Philippe", "Phoebe", "Phoebe's Stadium", "Picnic Basket", "Picnicker", "Pidgeot Spirit Link",
	"Piers", "Plasma Frigate", "Plume Fossil", "Plumeria", "PlusPower", "Po Town", "Poison Barb",
	"Poké Ball", "Poké Blower", "Poké Drawer", "Poké Healer", "Poké Kid", "Poké Maniac", "Poké Pad",
	"Poké Radar", "Poké Vital A", "PokéDex HANDY909", "PokéGear", "PokéNav", "PokéStop", "Pokédex",
	"Pokédex HANDY910is", "Pokégear 3.0", "Pokémon Breeder", "Pokémon Breeder Fields",
	"Pokémon Breeder's Nurturing", "Pokémon Catcher", "Pokémon Center", "Pokémon Center Lady",
	"Pokémon Circulator", "Pokémon Collector", "Pokémon Communication", "Pokémon Contest Hall",
	"Pokémon Fan Club", "Pokémon Flute", "Pokémon League Headquarters", "Pokémon March",
	"Pokémon Nurse", "Pokémon Park", "Pokémon Personality Test", "Pokémon Ranger", "Pokémon Rescue",
	"Pokémon Research Lab", "Pokémon Retriever", "Pokémon Reversal", "Pokémon Tower",
	"Pokémon Trader", "Poppy", "Postwick", "Pot Helmet", "Potion", "Pow! Hand Extension",
	"Power Charge", "Power Memory", "Power Plant", "Power Tablet", "Power Tree", "Powerglass",
	"Practice Studio", "Precious Trolley", "Premier Ball", "Premium Power Pro", "Prime Catcher",
	"Primordial Altar", "Prism Tower", "Prof. Oak's Research", "Professor Birch",
	"Professor Birch's Observations", "Professor Burnet", "Professor Cozmo's Discovery",
	"Professor Elm", "Professor Elm's Lecture", "Professor Elm's Training Method",
	"Professor Juniper", "Professor Kukui", "Professor Laventon", "Professor Oak",
	"Professor Oak's Hint", "Professor Oak's New Theory", "Professor Oak's Research",
	"Professor Oak's Setup", "Professor Oak's Visit", "Professor Rowan", "Professor Sada's Vitality",
	"Professor Sycamore", "Professor Turo's Scenario", "Professor's Letter", "Professor's Research",
	"Protection Cube", "Protective Goggles", "Protective Orb", "Psychic Cube 01", "Psychic Memory",
	"Psychic's Third Eye", "Punk Helmet", "Puzzle of Time", "Quad Stone", "Quick Ball", "Radio Tower",
	"Raifort", "Raihan", "Rainbow Brush", "Random Receiver", "Rapid Strike Scroll of Swirls",
	"Rapid Strike Scroll of the Flying Dragon", "Rapid Strike Scroll of the Skies",
	"Rapid Strike Style Mustard", "Rare Candy", "Rare Fossil", "Rayquaza Spirit Link", "Reboot Pod",
	"Recall", "Recycle", "Red & Blue", "Red Card", "Red's Challenge", "Redeemable Ticket",
	"Relic Hunter", "Repeat Ball", "Repel", "Rescue Board", "Rescue Carrier", "Rescue Scarf",
	"Rescue Stretcher", "Research Record", "Reserved Ticket", "Reset Stamp", "Resistance Gym",
	"Return Label", "Reversal Trigger", "Reverse Valley", "Revitalizer", "Revive", "Ribbon Badge",
	"Rigid Band", "Rika", "Riley", "Risky Ruins", "Rival", "Roark", "Robo Substitute Team Flare Gear",
	"Rock Chestplate", "Rock Guard", "Rocket's Admin.", "Rocket's Hideout", "Rocket's Minefield Gym",
	"Rocket's Mission", "Rocket's Poké Ball", "Rocket's Secret Experiment", "Rocket's Sneak Attack",
	"Rocket's Tricky Gym", "Rocky Helmet", "Roller Skater", "Roller Skates", "Root Fossil",
	"Root Fossil Lileep", "Rosa", "Rosa's Encouragement", "Rose", "Rose Tower", "Roseanne's Backup",
	"Roseanne's Research", "Roto-Stick", "Rotom Bike", "Rotom Dex", "Rotom Dex Poké Finder Mode",
	"Rotom Phone", "Rough Seas", "Roxanne", "Roxie", "Roxie's Performance", "Rubber Gloves",
	"Ruffian", "Rugged Helmet", "Ruin Wall", "Ruins of Alph", "Rust Syndicate Grunt", "Rusted Shield",
	"Rusted Sword", "Ryme", "Sabrina", "Sabrina & Brycen", "Sabrina's ESP", "Sabrina's Gaze",
	"Sabrina's Psychic Control", "Sabrina's Suggestion", "Sacred Ash", "Sacred Charm",
	"Saffron City Gym", "Sage's Training", "Saguaro", "Sail Fossil", "Salamence Spirit Link",
	"Salvatore", "Samson Oak", "Sceptile Spirit Link", "Schoolboy", "Schoolgirl",
	"Scizor Spirit Link", "Scoop Up", "Scoop Up Cyclone", "Scoop Up Net", "Scorched Earth", "Scott",
	"Scramble Switch", "Sea of Nothingness", "Secret Box", "Secret Mission", "Seeker", "Seer",
	"Serena", "Shadow Circle", "Shadow Triad", "Sharpedo Spirit Link", "Shauna", "Shauntal",
	"Shopping Center", "Shrine of Memories", "Shrine of Punishment", "Sidney", "Sidney's Stadium",
	"Siebold", "Sightseer", "Silent Lab", "Silver Bangle", "Silver Mirror",
	"Single Strike Scroll of Piercing", "Single Strike Scroll of Scorn",
	"Single Strike Scroll of the Fanged Dragon", "Single Strike Style Mustard", "Sitrus Berry",
	"Skaters' Park", "Skull Fossil", "Sky Field", "Sky Pillar", "Sky Seal Stone", "Skyarrow Bridge",
	"Skyla", "Sleep!", "Slowbro Spirit Link", "Slumbering Forest", "Snorlax Doll", "Snow Leaf Badge",
	"Snowpoint Temple", "Solid Rage", "Sonia", "Sophocles", "Sordward & Shielbert", "Space Center",
	"Spark", "Sparkling Crystal", "Sparkling Robe", "Special Charge", "Special Red Card",
	"Speed Stadium", "Spell Tag", "Spicy Seasoned Curry", "Spikemuth", "Spikemuth Gym", "Spirit Mask",
	"Spongy Gloves", "Sprout Tower", "Stadium Nav", "Star Piece", "Stark Mountain",
	"Startling Megaphone", "Stealthy Hood", "Steel Shelter", "Steelix Spirit Link", "Steven",
	"Steven's Advice", "Steven's Resolve", "Stormy Mountains", "Strange Cave", "Strange Timepiece",
	"Strength Charm", "Struggle Gloves", "Sunyshore City Gym", "Super Energy Removal",
	"Super Energy Removal 2", "Super Energy Retrieval", "Super Potion", "Super Rod", "Super Scoop Up",
	"Supereffective Glasses", "Superior Energy Retrieval", "Surfer", "Surfing Beach", "Surprise Box",
	"Surprise! Time Machine", "Survival Brace", "Suspicious Food Tin", "Sweet Honey", "Switch",
	"Switch Cart", "Switch Raft", "Switching Cups", "Swoop! Teleporter", "TM Machine", "TV Reporter",
	"Tag Call", "Tag Switch", "Target Whistle Team Flare Gear", "Tarragon", "Tate & Liza",
	"Team Aqua Admin", "Team Aqua Ball", "Team Aqua Belt", "Team Aqua Conspirator", "Team Aqua Grunt",
	"Team Aqua Hideout", "Team Aqua Schemer", "Team Aqua Technical Machine 01",
	"Team Aqua's Great Ball", "Team Aqua's Secret Base", "Team Flare Grunt",
	"Team Galactic's Invention G-101 Energy Gain", "Team Galactic's Invention G-103 Power Spray",
	"Team Galactic's Invention G-105 Poké Turn",
	"Team Galactic's Invention G-107 Technical Machine G", "Team Galactic's Invention G-109 SP Radar",
	"Team Galactic's Mars", "Team Galactic's Wager", "Team Magma Admin", "Team Magma Ball",
	"Team Magma Belt", "Team Magma Conspirator", "Team Magma Grunt", "Team Magma Hideout",
	"Team Magma Schemer", "Team Magma Technical Machine 01", "Team Magma's Great Ball",
	"Team Magma's Secret Base", "Team Plasma Badge", "Team Plasma Ball", "Team Plasma Grunt",
	"Team Rocket's Archer", "Team Rocket's Ariana", "Team Rocket's Bother-Bot",
	"Team Rocket's Evil Deeds", "Team Rocket's Factory", "Team Rocket's Giovanni",
	"Team Rocket's Great Ball", "Team Rocket's Handiwork", "Team Rocket's Hypnotizer",
	"Team Rocket's Petrel", "Team Rocket's Proton", "Team Rocket's Transceiver",
	"Team Rocket's Trickery", "Team Rocket's Venture Bomb", "Team Rocket's Watchtower",
	"Team Skull Grunt", "Team Star Grunt", "Team Yell Grunt", "Team Yell Towel", "Team Yell's Cheer",
	"Teammates", "Technical Machine TS-1", "Technical Machine TS-2", "Technical Machine: Blindside",
	"Technical Machine: Crisis Punch", "Technical Machine: Devolution",
	"Technical Machine: Evolution", "Technical Machine: Fluorite",
	"Technical Machine: Turbo Energize", "Techno Radar", "Telescopic Sight", "Temple of Sinnoh",
	"Tera Orb", "The Boss's Way", "The Masked Royal", "The Rocket's Training Gym",
	"The Rocket's Trap", "Thick Scale", "Thorton", "Thought Wave Machine", "Thunder Mountain",
	"Tickling Machine", "Tierno", "Time Capsule", "Time Shard", "Time-Space Distortion", "Timer Ball",
	"Tool Box", "Tool Jammer", "Tool Retriever", "Tool Scrapper", "Tormenting Spray",
	"Tower of Darkness", "Tower of Waters", "Town Map", "Town Store", "Town Volunteers",
	"Toy Catcher", "Trainers' Mail", "Training Center", "Training Court", "Transformation Tome",
	"Transparent Walls", "Trash Exchange", "Traveling Salesman", "Treasure Tracker", "Trekking Shoes",
	"Tremendous Bomb", "Trevor", "Trick Coin", "Trick Shovel", "Tropical Beach",
	"Tropical Tidal Wave", "Tropical Wind", "Tulip", "Turbo Patch", "Turffield Stadium", "Twins",
	"Twist Mountain", "Tyme", "Tyranitar Spirit Link", "U-Turn Board", "Ultimate Zone", "Ultra Ball",
	"Ultra Forest Kartenvoy", "Ultra Recon Squad", "Ultra Space", "Underground Expedition",
	"Underground Lake", "Undersea Ruins", "Unfair Stamp", "Unidentified Fossil", "Urbain",
	"Urn of Vitality", "VS Seeker", "Vengeful Punch", "Venture Bomb", "Venusaur Spirit Link",
	"Vermilion City Gym", "Victory Cup", "Victory Piece", "Virbank City Gym", "Viridian City Gym",
	"Viridian Forest", "Vitality Band", "Volkner", "Volkner's Philosophy", "Volo",
	"Wait and See Hammer", "Wait and See Turbo", "Waitress", "Wallace", "Wally", "Wally's Compassion",
	"Wally's Training", "Warp Point", "Water Cube 01", "Water Memory", "Weakness Guard",
	"Weakness Policy", "Weeding Gloves", "Wela Volcano Park", "Welcoming Lantern", "Welder",
	"Whitney", "Wicke", "Wide Lens", "Will", "Windstorm", "Windup Arm", "Winona", "Wishful Baton",
	"Wondrous Labyrinth", "Wondrous Patch", "Worker", "Wyndon Stadium", "Xerosic",
	"Xerosic's Machinations", "Xtransceiver", "Yell Horn", "Youngster", "Zinnia", "Zinnia's Resolve",
	"Zisu",
];

const ENERGY_NAMES = [
	"Aqua Energy", "Aromatic Grass Energy", "Aurora Energy", "Basic Darkness Energy",
	"Basic Fighting Energy", "Basic Fire Energy", "Basic Grass Energy", "Basic Lightning Energy",
	"Basic Metal Energy", "Basic Psychic Energy", "Basic Water Energy", "Beast Energy",
	"Blend Energy GrassFirePsychicDarkness", "Blend Energy WaterLightningFightingMetal",
	"Boomerang Energy", "Boost Energy", "Bounce Energy", "Bubbly Water Energy", "Burning Energy",
	"Call Energy", "Capture Energy", "Coating Metal Energy", "Counter Energy", "Crystal Energy",
	"Cyclone Energy", "Dangerous Energy", "Dark Metal Energy", "Darkness Energy",
	"Double Aqua Energy", "Double Colorless Energy", "Double Dragon Energy", "Double Magma Energy",
	"Double Rainbow Energy", "Double Turbo Energy", "Draw Energy", "Enriching Energy", "Fairy Energy",
	"Fighting Energy", "Fire Energy", "Flash Energy", "Full Heal Energy", "Fusion Strike Energy",
	"Gift Energy", "Grass Energy", "Growing Grass Energy", "Heal Energy", "Health Energy",
	"Heat Fire Energy", "Herbal Energy", "Hiding Darkness Energy", "Holon Energy FF",
	"Holon Energy GL", "Holon Energy WP", "Horror Psychic Energy", "Ignition Energy", "Impact Energy",
	"Jet Energy", "Legacy Energy", "Lightning Energy", "Lucky Energy", "Luminous Energy",
	"Magma Energy", "Magnetic Metal Energy", "Medical Energy", "Memory Energy", "Metal Energy",
	"Miracle Energy", "Mist Energy", "Multi Energy", "Mystery Energy", "Neo Upper Energy",
	"Nitro Fire Energy", "Plasma Energy", "Potion Energy", "Powerful Colorless Energy",
	"Prism Energy", "Psychic Energy", "R Energy", "Rainbow Energy", "Rapid Strike Energy",
	"React Energy", "Recover Energy", "Recycle Energy", "Regenerative Energy", "Rescue Energy",
	"Retro Energy", "Reversal Energy", "Rocky Fighting Energy", "SP Energy", "Scramble Energy",
	"Shadowy Darkness Energy", "Shield Energy", "Single Strike Energy", "Speed Lightning Energy",
	"Spiky Energy", "Spiral Energy", "Splash Energy", "Stone Fighting Energy", "Strong Energy",
	"Super Boost Energy", "Team Rocket's Energy", "Telepathic Psychic Energy", "Therapeutic Energy",
	"Treasure Energy", "Triple Acceleration Energy", "Twin Energy",
	"Unit Energy FightingDarknessFairy", "Unit Energy GrassFireWater",
	"Unit Energy LightningPsychicMetal", "Upper Energy", "V Guard Energy", "Voltaic Lightning Energy",
	"Warp Energy", "Wash Water Energy", "Water Energy", "Weakness Guard Energy", "Wonder Energy",
];
