"use strict";

// Every piece of text the app shows, in English and Danish.
// To change a wording, edit it here - no other file needs to change.
// Markers like {name} or {count} are filled in by the app when the text is shown.

const STRINGS = {
	en: {
		tagline: "Photograph a Pokémon card. See what it sells for.",
		languageSwitch: "Language",
		howItWorks: "How it works",
		step1Verb: "Snap",
		step1Rest: " the whole card, straight on, in good light.",
		step2Verb: "Check",
		step2Rest: " the name and number it read, then tap your card.",
		step3Verb: "See",
		step3Rest: " recent prices from Cardmarket and TCGplayer.",
		tryExample: "Try it with an example card",

		yourCard: "Your card",
		yourPhoto: "Your photo",
		nameLabel: "Name on the card",
		namePlaceholder: "e.g. Charizard",
		numberLabel: "Number in the bottom corner",
		numberPlaceholder: "e.g. 4/102",
		search: "Search",

		statusIdle: "Take a photo, or type the name and number from the card.",
		downloadingExample: "Downloading the example card…",
		exampleFailed: "Could not download the example card. Check the internet connection.",
		readerStarting: "Getting the text reader ready…",
		readerStartingSlow: "Getting the text reader ready (slow the first time)…",
		reading: "Reading the card…",
		readFailed: "Couldn't read the card. Type the name and number below, or try a sharper photo in better light.",
		unsureName: "Not sure what this card is called. Check the name, type the number from the bottom corner (like 86/110), then press Search. Sparkly cards are hard to read.",
		typeNumber: "{total} cards are called “{name}”; the ones that look most like your photo are first. To be sure, type the number from the bottom corner (like 86/110) and press Search.",
		numberNotFound: "No “{name}” card has the number {number}. Check the number in the bottom corner and press Search again.",
		needNameOrNumber: "Type the card's name or its number to search.",
		lookingUp: "Looking up prices…",
		foundOne: "Found it.",
		foundMany: "Found {count} possible cards. Tap yours.",
		comparingPictures: "Comparing pictures…",
		comparingProgress: "Comparing pictures… {done} of {total}",
		foundManyByLook: "Found {count} possible cards, closest look first. Tap yours.",
		bestMatchOpened: "This looks like your card. Not it? Tap the right one below.",
		bestMatch: "Best match",
		noMatch: "No cards matched. Check the name and number against the card and search again.",
		apiDown: "The price database didn't answer. Wait a moment, then press Search.",

		resultsTitle: "Which one is yours?",
		matchExact: "Cards named “{name}” with number {number}.",
		matchAnySet: "Cards named “{name}” with number {number}, from any set.",
		matchNameTotal: "Cards named “{name}” from a set of {total} cards. Check the number.",
		matchByLook: "The name and number couldn't both be read, so these are the cards that fit part of it, closest look first.",
		matchSetSizeLook: "Only the set size could be read, so these are the cards from sets of {total} cards, closest look first.",
		matchNumberNameMissed: "Nothing named “{name}” has number {number}, so here is every card with that number. Check the name.",
		matchNumberOnly: "Every card with number {number}.",
		matchNameOnly: "Every “{name}” card, newest first. Add the number from the bottom corner to narrow it down.",
		matchNumberNoTotal: "Cards with number {number}, newest first. Add the name to narrow it down.",
		showingFirst: " Showing the first {count}.",

		noPrices: "Nobody has sold this card on Cardmarket or TCGplayer recently, so there is no price yet.",
		soldOnEbay: "See what it has sold for on eBay",
		notYours: "Not your card? Fix the name or number above and press Search.",
		ungraded: "These are prices for ungraded cards. A scratched, bent or faded card sells for less.",
		pricesFrom: "Prices from {date}",
		weeksOld: "{count} weeks old",
		monthsOld: "{count} months old",

		cardmarketStat: "Cardmarket · Europe",
		cardmarketPrice: "Price",
		euro: "Euro",
		kroner: "Kroner",
		avg30: "30-day average",
		avg7: "7-day average",
		trendPrice: "Trend",
		averageSellPrice: "Average sale",
		lowPrice: "Cheapest listing",
		reverseHoloAvg30: "Reverse holo, 30-day average",
		reverseHoloTrend: "Reverse holo, trend",
		openCardmarket: "Open on Cardmarket",

		tcgplayerStat: "TCGplayer · USA",
		tcgplayerVersion: "Version",
		tcgplayerMarket: "Market",
		tcgplayerLowest: "Lowest",
		marketPrice: "market price",
		holofoil: "Holo",
		normal: "Normal",
		reverseHolofoil: "Reverse holo",
		firstEditionHolofoil: "1st edition holo",
		firstEditionNormal: "1st edition",
		unlimitedHolofoil: "Unlimited holo",
		unlimited: "Unlimited",
		openTcgplayer: "Open on TCGplayer",

		footerBefore: "Card data and prices come from the free ",
		footerLink: "Pokémon TCG API",
		footerAfter: ". Not made by or linked to Pokémon, Cardmarket or TCGplayer.",
		appVersion: "Kortpris version {version}",
		currencyLabel: "Currency",
		ratesFrom: "Exchange rates from {date} (European Central Bank).",
		ratesMissing: "Exchange rates couldn't load, so prices are shown in euro for now.",
		gradedTitle: "Graded cards (PSA)",
		gradedExplain: "PSA rates a card's condition from 1 to 10 and seals it in a case. A PSA 10 can sell for many times the prices above. These links show what graded copies of this card really sold for.",
		gradedEbay: "{grade} sales on eBay",
		gradedPriceCharting: "All grades on PriceCharting",
		gradedGrade: "Grade",
		gradedMiddle: "Middle price",
		gradedDollars: "In dollars",
		gradedSales: "Sales",
		gradedFrom: "The middle price of this card's recent eBay sales in each grade, from PokemonPriceTracker. The fewer the sales, the less certain the price.",
		gradedAllVersions: "They cover all versions of the card together, so a PSA reverse holo can be worth more than shown.",
		gradedFetchToggle: "Fetch PSA prices automatically",
		gradedOff: "Tick the box to fetch this card's PSA prices, and those of every card you open after it. The free price service allows about 50 cards a day, so it stays off until you need it.",
		gradedLoading: "Fetching PSA prices…",
		gradedNone: "No PSA sales of this card were found.",
		gradedFailed: "The PSA prices couldn't be fetched right now. Open the card again in a minute.",

		scanBar: "Scan",
		takePhoto: "Take photo",
		choosePhoto: "Choose photo",

		views: "Screens",
		viewScan: "Scan",
		viewCollection: "My cards",
		addToCollection: "Add to my cards",
		addAnother: "Add one more",
		inCollection: "You have {count} in My cards.",
		inCollectionVersion: "You have {count} of this version in My cards.",
		whichVersion: "Which version is yours?",
		versionHint: "Reverse holo: the card sparkles everywhere except the picture. Holo: the picture itself sparkles.",
		storageBlocked: "This browser won't let the app save anything, so My cards can't be kept. Private browsing does this.",
		collectionEmpty: "No cards yet. Scan a card, then press “Add to my cards”.",
		collectionSearchLabel: "Search my cards",
		collectionSearchPlaceholder: "Name, set or number",
		searchFoundOne: "1 card found",
		searchFound: "{count} cards found",
		searchWorth: "worth {price}",
		searchNothing: "No card matches “{query}”.",
		totalValue: "Total value",
		cardCountOne: "1 card",
		cardCount: "{count} cards",
		valueBasis: "Cardmarket prices (TCGplayer where Cardmarket has none)",
		notInTotal: "{count} without any price, so not in the total.",
		updatePrices: "Update prices",
		updatingPrices: "Updating prices…",
		pricesUpdated: "Prices updated.",
		refreshFailed: "The price database didn't answer. Try again in a moment.",
		noPrice: "no price",
		each: "{price} each",
		allOfThem: "{price} for all",
		oneFewer: "One fewer",
		oneMore: "One more",
		savedOnPhone: "My cards is saved on this phone only. Clearing the browser's data deletes it.",

		claudeTitle: "Read cards with Claude",
		claudeOn: "On",
		claudeOff: "Off",
		claudeExplain: "Claude reads cards far more reliably than the built-in reader: worn cards, shiny foil, and cards in other languages. It needs your own Anthropic API key, and each photo costs roughly 20–25 øre (about 3 US cents) on your Anthropic account.",
		claudeKeyLabel: "Anthropic API key",
		claudeKeyPlaceholder: "sk-ant-…",
		claudeKeyHelpBefore: "Make a key at ",
		claudeKeyHelpAfter: ". Set a monthly spending limit there too, so a mistake can never cost much.",
		claudeSave: "Save key",
		claudeRemove: "Remove key",
		claudeSaved: "Saved. New photos are read by Claude.",
		claudeRemoved: "Removed. Photos are read by the built-in reader again.",
		claudeKeyShape: "That doesn't look like an Anthropic API key. They start with “sk-ant-”.",
		claudeSaveFailed: "This browser won't let the app save the key. Private browsing does this.",
		claudePrivacy: "The key is saved on this phone only and is sent only to Anthropic. Photos you scan are sent to Anthropic to be read.",
		claudeReading: "Claude is reading the card…",
		claudeNotACard: "Claude doesn't see a Pokémon card in this photo. Try again with the whole card in view.",
		claudeKeyWrong: "Claude didn't accept your API key, so the built-in reader was used. Check the key under “Read cards with Claude”.",
		claudeNoCredit: "Your Anthropic account is out of credit, so the built-in reader was used.",
		claudeBusy: "Claude is busy right now, so the built-in reader was used.",
		claudeFailed: "Claude couldn't read this photo, so the built-in reader was used.",

		accountTitle: "Your account",
		accountExplain: "Sign in to keep your cards in an account and see them on any phone. Everyone in the family can have their own.",
		accountModes: "Sign in or create an account",
		signIn: "Sign in",
		createAccount: "Create account",
		signingIn: "Signing in…",
		creatingAccount: "Creating account…",
		usernameLabel: "Username",
		usernameHint: "3–20 characters: letters a–z, numbers, - and _. Don't use your full name.",
		passwordLabel: "Password",
		passwordAgainLabel: "Password again",
		showPassword: "Show",
		hidePassword: "Hide",
		passwordTip: "Tip: three or four random words are strong and easy to remember, like “purple tiger eats rockets”.",
		passwordTooShort: "At least {min} characters. {left} to go.",
		passwordHasUsername: "Don't put your username in the password.",
		passwordTooSimple: "Too easy to guess. Try three or four random words instead.",
		passwordStrong: "Strong password.",
		passwordCheckerLoading: "Checking the password…",
		passwordCheckerFailed: "The password checker couldn't be downloaded. Check the internet connection.",
		passwordsDiffer: "The two passwords aren't the same.",
		usernameInvalid: "Usernames are 3–20 characters: letters a–z, numbers, - and _.",
		needPassword: "Type your password.",
		accountCreated: "Account created. Welcome, {name}!",
		signedInAs: "Signed in as",
		signOut: "Sign out",
		phoneCardsOne: "This phone has 1 card saved outside any account.",
		phoneCards: "This phone has {count} cards saved outside any account.",
		moveCards: "Move them into this account",
		cardsMoved: "Moved. They're in your account now.",
		loadingAccountCards: "Loading your cards…",
		savedInAccount: "These cards are saved in {name}'s account and show up on every phone {name} signs in on.",
		notSaved: "Not saved to the account.",
		usernameTaken: "That username is taken. Pick another one.",
		wrongLogin: "Wrong username or password.",
		tooManyTries: "Too many tries. Wait a few minutes, then try again.",
		passwordRejected: "That password is too simple.",
		signUpClosed: "New accounts are switched off. Ask the grown-up who set up Kortpris.",
		accountsNotSetUp: "Accounts aren't switched on in Firebase yet. Finish SETUP-ACCOUNTS.md (steps 3 to 6).",
		noConnection: "No internet connection. Try again when you're online.",
		permissionDenied: "This account isn't allowed to open these cards.",
		accountFailed: "Something went wrong ({code}). Try again.",
		accountsOffline: "Accounts can't load right now. Your cards on this phone still work.",

		// Kids mode: big pictures, few words, and the phone reads out loud.
		kidsMode: "Kids",
		kidsModeLabel: "Kids mode: big buttons, and the phone reads out loud",
		readAloud: "Read aloud",
		kidIdle: "Take a photo of your card",
		kidBusy: "One moment…",
		kidFound: "Found it!",
		kidPickOne: "Which card is yours? Tap it.",
		kidNotFound: "Couldn't find the card. Try a new photo.",
		kidTryLater: "Try again in a moment.",
		kidPriceAbout: "about {price}",
		kidPriceUnder: "under {price}",
		kidSave: "Save card",
		kidSaveAnother: "Save one more",
		kidHave: "You have {count}",
		coins: "{count} of 5 coins",
		sayKidsModeOn: "Kids mode is on. Press the yellow button and take a photo of your card.",
		sayTakePhoto: "Take a photo of the whole card.",
		sayChoosePhoto: "Choose a photo of your card.",
		sayLooking: "One moment. I'm looking at the card.",
		sayPickOne: "Which card is yours? Tap it.",
		sayNotFound: "I couldn't find the card. Take a new photo with the whole card in it.",
		sayTryLater: "The price list isn't answering. Try again in a moment.",
		sayWorth: "{name}. It's worth {price}.",
		sayWorthVersion: "{name}, {version}. It's worth {price}.",
		sayWow: "Wow! {sentence}",
		sayNoPrice: "{name}. I don't know what it's worth.",
		saySaved: "Saved in My cards!",
		sayCollection: "Your cards are worth {price} in all.",
		sayCollectionEmpty: "You have no cards yet.",
		spokenAbout: "about {amount}",
		spokenUnder: "less than {amount}",
		unitOneDKK: "krone",
		unitManyDKK: "kroner",
		unitOneEUR: "euro",
		unitManyEUR: "euros",
		unitOneGBP: "pound",
		unitManyGBP: "pounds",
		unitOneIDR: "rupiah",
		unitManyIDR: "rupiah",
	},

	da: {
		tagline: "Fotografér et Pokémon-kort. Se hvad det sælges for.",
		languageSwitch: "Sprog",
		howItWorks: "Sådan virker det",
		step1Verb: "Fotografér",
		step1Rest: " hele kortet lige forfra i godt lys.",
		step2Verb: "Tjek",
		step2Rest: " navn og nummer, og tryk på dit kort.",
		step3Verb: "Se",
		step3Rest: " de seneste priser fra Cardmarket og TCGplayer.",
		tryExample: "Prøv med et eksempelkort",

		yourCard: "Dit kort",
		yourPhoto: "Dit billede",
		nameLabel: "Navn på kortet",
		namePlaceholder: "f.eks. Charizard",
		numberLabel: "Nummer i hjørnet forneden",
		numberPlaceholder: "f.eks. 4/102",
		search: "Søg",

		statusIdle: "Tag et billede, eller skriv navn og nummer fra kortet.",
		downloadingExample: "Henter eksempelkortet…",
		exampleFailed: "Kunne ikke hente eksempelkortet. Tjek internetforbindelsen.",
		readerStarting: "Gør tekstlæseren klar…",
		readerStartingSlow: "Gør tekstlæseren klar (tager lidt tid første gang)…",
		reading: "Læser kortet…",
		readFailed: "Kunne ikke læse kortet. Skriv navn og nummer herunder, eller prøv et skarpere billede i bedre lys.",
		unsureName: "Usikker på, hvad kortet hedder. Tjek navnet, skriv nummeret fra hjørnet forneden (fx 86/110), og tryk så på Søg. Glimtende kort er svære at læse.",
		typeNumber: "{total} kort hedder »{name}«; dem, der ligner dit billede mest, står først. Skriv nummeret fra hjørnet forneden (fx 86/110), og tryk på Søg for at være sikker.",
		numberNotFound: "Intet »{name}«-kort har nummeret {number}. Tjek nummeret i hjørnet forneden, og tryk på Søg igen.",
		needNameOrNumber: "Skriv kortets navn eller nummer for at søge.",
		lookingUp: "Slår priser op…",
		foundOne: "Fundet!",
		foundMany: "Fandt {count} mulige kort. Tryk på dit.",
		comparingPictures: "Sammenligner billeder…",
		comparingProgress: "Sammenligner billeder… {done} af {total}",
		foundManyByLook: "Fandt {count} mulige kort, det mest lignende først. Tryk på dit.",
		bestMatchOpened: "Det ligner dit kort. Forkert? Tryk på det rigtige herunder.",
		bestMatch: "Bedste match",
		noMatch: "Ingen kort passede. Sammenlign navn og nummer med kortet, og søg igen.",
		apiDown: "Prisdatabasen svarede ikke. Vent lidt, og tryk så på Søg.",

		resultsTitle: "Hvilket er dit?",
		matchExact: "Kort med navnet »{name}« og nummer {number}.",
		matchAnySet: "Kort med navnet »{name}« og nummer {number}, fra alle sæt.",
		matchNameTotal: "Kort med navnet »{name}« fra et sæt med {total} kort. Tjek nummeret.",
		matchByLook: "Navn og nummer kunne ikke begge læses, så her er kortene, der passer med en del af det, det mest lignende først.",
		matchSetSizeLook: "Kun sættets størrelse kunne læses, så her er kortene fra sæt med {total} kort, det mest lignende først.",
		matchNumberNameMissed: "Intet kort med navnet »{name}« har nummer {number}, så her er alle kort med det nummer. Tjek navnet.",
		matchNumberOnly: "Alle kort med nummer {number}.",
		matchNameOnly: "Alle »{name}«-kort, nyeste først. Tilføj nummeret fra hjørnet forneden for at indsnævre søgningen.",
		matchNumberNoTotal: "Kort med nummer {number}, nyeste først. Tilføj navnet for at indsnævre søgningen.",
		showingFirst: " Viser de første {count}.",

		noPrices: "Ingen har solgt kortet på Cardmarket eller TCGplayer for nylig, så der er ingen pris endnu.",
		soldOnEbay: "Se, hvad det er solgt for på eBay",
		notYours: "Ikke dit kort? Ret navn eller nummer ovenfor, og tryk på Søg.",
		ungraded: "Priserne gælder ugraderede kort. Et ridset, bøjet eller falmet kort sælges for mindre.",
		pricesFrom: "Priser fra {date}",
		weeksOld: "{count} uger gamle",
		monthsOld: "{count} måneder gamle",

		cardmarketStat: "Cardmarket · Europa",
		cardmarketPrice: "Pris",
		euro: "Euro",
		kroner: "Kroner",
		avg30: "Gennemsnit, 30 dage",
		avg7: "Gennemsnit, 7 dage",
		trendPrice: "Trend",
		averageSellPrice: "Gennemsnitligt salg",
		lowPrice: "Billigste udbud",
		reverseHoloAvg30: "Reverse holo, gennemsnit 30 dage",
		reverseHoloTrend: "Reverse holo, trend",
		openCardmarket: "Åbn på Cardmarket",

		tcgplayerStat: "TCGplayer · USA",
		tcgplayerVersion: "Version",
		tcgplayerMarket: "Marked",
		tcgplayerLowest: "Laveste",
		marketPrice: "markedspris",
		holofoil: "Holo",
		normal: "Normal",
		reverseHolofoil: "Reverse holo",
		firstEditionHolofoil: "1. udgave, holo",
		firstEditionNormal: "1. udgave",
		unlimitedHolofoil: "Unlimited, holo",
		unlimited: "Unlimited",
		openTcgplayer: "Åbn på TCGplayer",

		footerBefore: "Kortdata og priser kommer fra det gratis ",
		footerLink: "Pokémon TCG API",
		footerAfter: ". Ikke lavet af eller tilknyttet Pokémon, Cardmarket eller TCGplayer.",
		appVersion: "Kortpris version {version}",
		currencyLabel: "Valuta",
		ratesFrom: "Valutakurser fra {date} (Den Europæiske Centralbank).",
		ratesMissing: "Valutakurserne kunne ikke hentes, så priserne vises i euro indtil videre.",
		gradedTitle: "Graderede kort (PSA)",
		gradedExplain: "PSA bedømmer et korts stand fra 1 til 10 og forsegler det i et etui. Et PSA 10 kan sælges for mange gange priserne ovenfor. Linkene viser, hvad graderede eksemplarer af kortet faktisk er solgt for.",
		gradedEbay: "{grade}-salg på eBay",
		gradedPriceCharting: "Alle karakterer på PriceCharting",
		gradedGrade: "Karakter",
		gradedMiddle: "Mellempris",
		gradedDollars: "I dollar",
		gradedSales: "Salg",
		gradedFrom: "Mellemprisen for kortets seneste eBay-salg i hver karakter, fra PokemonPriceTracker. Jo færre salg, jo mere usikker er prisen.",
		gradedAllVersions: "Salgene gælder alle kortets versioner under ét, så et PSA-gradet reverse holo kan være mere værd end vist.",
		gradedFetchToggle: "Hent PSA-priser automatisk",
		gradedOff: "Sæt flueben for at hente kortets PSA-priser og priserne på alle kort, du åbner bagefter. Den gratis pristjeneste giver cirka 50 kort om dagen, så det er slået fra, til du har brug for det.",
		gradedLoading: "Henter PSA-priser …",
		gradedNone: "Der blev ikke fundet PSA-salg af kortet.",
		gradedFailed: "PSA-priserne kunne ikke hentes lige nu. Åbn kortet igen om et minut.",

		scanBar: "Scan",
		takePhoto: "Tag billede",
		choosePhoto: "Vælg billede",

		views: "Skærme",
		viewScan: "Scan",
		viewCollection: "Mine kort",
		addToCollection: "Læg i Mine kort",
		addAnother: "Læg én mere i",
		inCollection: "Du har {count} i Mine kort.",
		inCollectionVersion: "Du har {count} af denne version i Mine kort.",
		whichVersion: "Hvilken version har du?",
		versionHint: "Reverse holo: kortet glimter overalt undtagen på billedet. Holo: selve billedet glimter.",
		storageBlocked: "Browseren tillader ikke, at appen gemmer noget, så Mine kort kan ikke gemmes. Privat browsing gør det.",
		collectionEmpty: "Ingen kort endnu. Scan et kort, og tryk så på »Læg i Mine kort«.",
		collectionSearchLabel: "Søg i mine kort",
		collectionSearchPlaceholder: "Navn, sæt eller nummer",
		searchFoundOne: "1 kort fundet",
		searchFound: "{count} kort fundet",
		searchWorth: "værd {price}",
		searchNothing: "Intet kort passer med »{query}«.",
		totalValue: "Samlet værdi",
		cardCountOne: "1 kort",
		cardCount: "{count} kort",
		valueBasis: "Cardmarket-priser (TCGplayer, hvor Cardmarket ingen har)",
		notInTotal: "{count} uden nogen pris, så de er ikke med i summen.",
		updatePrices: "Opdater priser",
		updatingPrices: "Opdaterer priser…",
		pricesUpdated: "Priserne er opdateret.",
		refreshFailed: "Prisdatabasen svarede ikke. Prøv igen om lidt.",
		noPrice: "ingen pris",
		each: "{price} pr. stk.",
		allOfThem: "{price} for alle",
		oneFewer: "Én mindre",
		oneMore: "Én mere",
		savedOnPhone: "Mine kort gemmes kun på denne telefon. Hvis browserens data slettes, forsvinder de.",

		claudeTitle: "Læs kort med Claude",
		claudeOn: "Til",
		claudeOff: "Fra",
		claudeExplain: "Claude læser kort langt mere pålideligt end den indbyggede læser: slidte kort, blankt folie og kort på andre sprog. Det kræver din egen Anthropic API-nøgle, og hvert billede koster cirka 20–25 øre på din Anthropic-konto.",
		claudeKeyLabel: "Anthropic API-nøgle",
		claudeKeyPlaceholder: "sk-ant-…",
		claudeKeyHelpBefore: "Lav en nøgle på ",
		claudeKeyHelpAfter: ". Sæt også en månedlig beløbsgrænse dér, så en fejl aldrig kan blive dyr.",
		claudeSave: "Gem nøgle",
		claudeRemove: "Fjern nøgle",
		claudeSaved: "Gemt. Nye billeder læses af Claude.",
		claudeRemoved: "Fjernet. Billeder læses igen af den indbyggede læser.",
		claudeKeyShape: "Det ligner ikke en Anthropic API-nøgle. De starter med »sk-ant-«.",
		claudeSaveFailed: "Browseren tillader ikke, at appen gemmer nøglen. Privat browsing gør det.",
		claudePrivacy: "Nøglen gemmes kun på denne telefon og sendes kun til Anthropic. Billeder, du scanner, sendes til Anthropic for at blive læst.",
		claudeReading: "Claude læser kortet…",
		claudeNotACard: "Claude kan ikke se et Pokémon-kort på billedet. Prøv igen med hele kortet i billedet.",
		claudeKeyWrong: "Claude accepterede ikke din API-nøgle, så den indbyggede læser blev brugt. Tjek nøglen under »Læs kort med Claude«.",
		claudeNoCredit: "Din Anthropic-konto har ikke mere kredit, så den indbyggede læser blev brugt.",
		claudeBusy: "Claude har travlt lige nu, så den indbyggede læser blev brugt.",
		claudeFailed: "Claude kunne ikke læse billedet, så den indbyggede læser blev brugt.",

		accountTitle: "Din konto",
		accountExplain: "Log ind for at gemme dine kort på en konto og se dem på enhver telefon. Alle i familien kan have deres egen.",
		accountModes: "Log ind eller opret en konto",
		signIn: "Log ind",
		createAccount: "Opret konto",
		signingIn: "Logger ind…",
		creatingAccount: "Opretter konto…",
		usernameLabel: "Brugernavn",
		usernameHint: "3–20 tegn: bogstaverne a–z, tal, - og _. Brug ikke dit fulde navn.",
		passwordLabel: "Adgangskode",
		passwordAgainLabel: "Adgangskode igen",
		showPassword: "Vis",
		hidePassword: "Skjul",
		passwordTip: "Tip: tre-fire tilfældige ord er stærke og lette at huske, fx »lilla tiger spiser raketter«.",
		passwordTooShort: "Mindst {min} tegn. {left} mere.",
		passwordHasUsername: "Brug ikke dit brugernavn i adgangskoden.",
		passwordTooSimple: "For let at gætte. Prøv tre-fire tilfældige ord i stedet.",
		passwordStrong: "Stærk adgangskode.",
		passwordCheckerLoading: "Tjekker adgangskoden…",
		passwordCheckerFailed: "Adgangskode-tjekket kunne ikke hentes. Tjek internetforbindelsen.",
		passwordsDiffer: "De to adgangskoder er ikke ens.",
		usernameInvalid: "Brugernavne er 3–20 tegn: bogstaverne a–z, tal, - og _.",
		needPassword: "Skriv din adgangskode.",
		accountCreated: "Kontoen er oprettet. Velkommen, {name}!",
		signedInAs: "Logget ind som",
		signOut: "Log ud",
		phoneCardsOne: "Denne telefon har 1 kort gemt uden for en konto.",
		phoneCards: "Denne telefon har {count} kort gemt uden for en konto.",
		moveCards: "Flyt dem ind på denne konto",
		cardsMoved: "Flyttet. De ligger nu på din konto.",
		loadingAccountCards: "Henter dine kort…",
		savedInAccount: "Kortene er gemt på kontoen »{name}« og vises på alle telefoner, hvor {name} logger ind.",
		notSaved: "Ikke gemt på kontoen.",
		usernameTaken: "Det brugernavn er taget. Vælg et andet.",
		wrongLogin: "Forkert brugernavn eller adgangskode.",
		tooManyTries: "For mange forsøg. Vent et par minutter, og prøv igen.",
		passwordRejected: "Adgangskoden er for simpel.",
		signUpClosed: "Nye konti er slået fra. Spørg den voksne, der har sat Kortpris op.",
		accountsNotSetUp: "Konti er ikke slået til i Firebase endnu. Gør SETUP-ACCOUNTS.md færdig (trin 3 til 6).",
		noConnection: "Ingen internetforbindelse. Prøv igen, når du er online.",
		permissionDenied: "Denne konto må ikke åbne disse kort.",
		accountFailed: "Noget gik galt ({code}). Prøv igen.",
		accountsOffline: "Konti kan ikke indlæses lige nu. Kortene på denne telefon virker stadig.",

		// Børnetilstand: store billeder, få ord, og telefonen læser højt.
		kidsMode: "Børn",
		kidsModeLabel: "Børnetilstand: store knapper, og telefonen læser højt",
		readAloud: "Læs højt",
		kidIdle: "Tag et billede af dit kort",
		kidBusy: "Et øjeblik…",
		kidFound: "Fundet!",
		kidPickOne: "Hvilket kort er dit? Tryk på det.",
		kidNotFound: "Kunne ikke finde kortet. Prøv et nyt billede.",
		kidTryLater: "Prøv igen om lidt.",
		kidPriceAbout: "cirka {price}",
		kidPriceUnder: "under {price}",
		kidSave: "Gem kortet",
		kidSaveAnother: "Gem ét mere",
		kidHave: "Du har {count}",
		coins: "{count} af 5 mønter",
		sayKidsModeOn: "Børnetilstand er slået til. Tryk på den gule knap, og tag et billede af dit kort.",
		sayTakePhoto: "Tag et billede af hele kortet.",
		sayChoosePhoto: "Vælg et billede af dit kort.",
		sayLooking: "Et øjeblik. Jeg kigger på kortet.",
		sayPickOne: "Hvilket kort er dit? Tryk på det.",
		sayNotFound: "Jeg kunne ikke finde kortet. Tag et nyt billede, hvor hele kortet er med.",
		sayTryLater: "Prislisten svarer ikke. Prøv igen om lidt.",
		sayWorth: "{name}. Det er {price} værd.",
		sayWorthVersion: "{name}, {version}. Det er {price} værd.",
		sayWow: "Wow! {sentence}",
		sayNoPrice: "{name}. Jeg ved ikke, hvad det er værd.",
		saySaved: "Gemt i Mine kort!",
		sayCollection: "Dine kort er {price} værd i alt.",
		sayCollectionEmpty: "Du har ingen kort endnu.",
		spokenAbout: "cirka {amount}",
		spokenUnder: "under {amount}",
		unitOneDKK: "krone",
		unitManyDKK: "kroner",
		unitOneEUR: "euro",
		unitManyEUR: "euro",
		unitOneGBP: "pund",
		unitManyGBP: "pund",
		unitOneIDR: "rupiah",
		unitManyIDR: "rupiah",
	},
};

// Numbers, money and dates are written the way each language expects:
// "18.114,21 kr." in Danish, "DKK 18,114.21" in English.
const NUMBER_LOCALES = {
	en: "en-GB",
	da: "da-DK",
};
