"use strict";

// Every piece of text the app shows, in English and Danish.
// To change a wording, edit it here - no other file needs to change.
// Markers like {name} or {count} are filled in by the app when the text is shown.

const STRINGS = {
	en: {
		tagline: "Photograph a Pokémon card. See what it sells for.",
		languageSwitch: "Language",
		howItWorks: "How it works",
		step1Verb: "Snap",
		step1Rest: " the whole card, straight on, in good light.",
		step2Verb: "Check",
		step2Rest: " the name and number it read, then tap your card.",
		step3Verb: "See",
		step3Rest: " recent prices from Cardmarket and TCGplayer.",
		tryExample: "Try it with an example card",

		yourCard: "Your card",
		yourPhoto: "Your photo",
		nameLabel: "Name on the card",
		namePlaceholder: "e.g. Charizard",
		numberLabel: "Number in the bottom corner",
		numberPlaceholder: "e.g. 4/102",
		search: "Search",

		statusIdle: "Take a photo, or type the name and number from the card.",
		downloadingExample: "Downloading the example card…",
		exampleFailed: "Could not download the example card. Check the internet connection.",
		readerStarting: "Getting the text reader ready…",
		readerStartingSlow: "Getting the text reader ready (slow the first time)…",
		reading: "Reading the card…",
		readFailed: "Couldn't read the card. Type the name and number below, or try a sharper photo in better light.",
		unsureName: "Not sure what this card is called. Check the name, type the number from the bottom corner (like 86/110), then press Search. Sparkly cards are hard to read.",
		typeNumber: "{total} cards are called “{name}”; the ones that look most like your photo are first. To be sure, type the number from the bottom corner (like 86/110) and press Search.",
		numberNotFound: "No “{name}” card has the number {number}. Check the number in the bottom corner and press Search again.",
		needNameOrNumber: "Type the card's name or its number to search.",
		lookingUp: "Looking up prices…",
		foundOne: "Found it.",
		foundMany: "Found {count} possible cards. Tap yours.",
		comparingPictures: "Comparing pictures…",
		comparingProgress: "Comparing pictures… {done} of {total}",
		foundManyByLook: "Found {count} possible cards, closest look first. Tap yours.",
		bestMatchOpened: "This looks like your card. Not it? Tap the right one below.",
		learnedOpened: "Recognised: you've shown me this card before. Not it? Type the right name and number, and press Search.",
		learnedChecking: "Recognised: you've shown me this card before. Checking the text on it…",
		learnedOtherPrint: "The name and number on the card belong to another print of the same picture, so that one is shown, not the card you showed me before.",
		learnedSuggested: "Couldn't read the card, but it looks a bit like cards you've shown me before. If yours is below, tap it. If not, type the name and number.",
		bestMatch: "Best match",
		seenBefore: "Seen before",
		noMatch: "No cards matched. Check the name and number against the card and search again.",
		apiDown: "The price database didn't answer. Wait a moment, then press Search.",
		apiTooMany: "The price database has had too many lookups from this internet connection today. Try again later, or on mobile data.",

		resultsTitle: "Which one is yours?",
		matchExact: "Cards named “{name}” with number {number}.",
		matchAnySet: "Cards named “{name}” with number {number}, from any set.",
		matchNameTotal: "Cards named “{name}” from a set of {total} cards. Check the number.",
		matchByLook: "The name and number couldn't both be read, so these are the cards that fit part of it, closest look first.",
		matchSetSizeLook: "Only the set size could be read, so these are the cards from sets of {total} cards, closest look first.",
		matchLearned: "Recognised from an earlier photo.",
		matchLearnedSuggested: "Cards you've shown me before that look a bit like the photo, closest first.",
		matchNumberNameMissed: "Nothing named “{name}” has number {number}, so here is every card with that number. Check the name.",
		matchNumberOnly: "Every card with number {number}.",
		matchNameOnly: "Every “{name}” card, newest first. Add the number from the bottom corner to narrow it down.",
		matchNumberNoTotal: "Cards with number {number}, newest first. Add the name to narrow it down.",
		showingFirst: " Showing the first {count}.",

		noPrices: "Nobody has sold this card on Cardmarket or TCGplayer recently, so there is no price yet.",
		pricesFailed: "The price database didn't answer, so the prices can't be shown right now. Search again in a moment.",
		soldOnEbay: "See what it has sold for on eBay",
		notYours: "Not your card? Fix the name or number above and press Search.",
		ungraded: "These are prices for ungraded cards. A scratched, bent or faded card sells for less.",
		pricesFrom: "Prices from {date}",
		weeksOld: "{count} weeks old",
		monthsOld: "{count} months old",

		cardmarketStat: "Cardmarket · Europe",
		cardmarketPrice: "Price",
		euro: "Euro",
		kroner: "Kroner",
		avg30: "30-day average",
		avg7: "7-day average",
		trendPrice: "Trend",
		averageSellPrice: "Average sale",
		lowPrice: "Cheapest listing",
		reverseHoloAvg30: "Reverse holo, 30-day average",
		reverseHoloTrend: "Reverse holo, trend",
		openCardmarket: "Open on Cardmarket",

		tcgplayerStat: "TCGplayer · USA",
		tcgplayerVersion: "Version",
		tcgplayerMarket: "Market",
		tcgplayerLowest: "Lowest",
		marketPrice: "market price",
		holofoil: "Holo",
		normal: "Normal",
		reverseHolofoil: "Reverse holo",
		firstEditionHolofoil: "1st edition holo",
		firstEditionNormal: "1st edition",
		unlimitedHolofoil: "Unlimited holo",
		unlimited: "Unlimited",
		openTcgplayer: "Open on TCGplayer",

		footerBefore: "Card data and prices come from the free card database ",
		footerLink: "TCGdex",
		footerAfter: ". Not made by or linked to Pokémon, Cardmarket or TCGplayer.",
		appVersion: "Kortpris version {version}",
		currencyLabel: "Currency",
		ratesFrom: "Exchange rates from {date} (European Central Bank).",
		ratesMissing: "Exchange rates couldn't load, so prices are shown in euro for now.",
		gradedTitle: "Graded cards (PSA)",
		gradedExplain: "PSA rates a card's condition from 1 to 10 and seals it in a case. A PSA 10 can sell for many times the prices above. These links show what graded copies of this card really sold for.",
		gradedEbay: "{grade} sales on eBay",
		gradedPriceCharting: "All grades on PriceCharting",
		gradedGrade: "Grade",
		gradedPrice: "Price",
		gradedDollars: "In dollars",
		gradedSales: "Sales",
		gradedFrom: "Each grade's price from this card's eBay sales, worked out by PokemonPriceTracker: recent sales count most, and odd ones are left out. The fewer the sales, the less certain the price.",
		gradedMore: "Last sales, other companies and eBay",
		gradedLastSale: "Last sale",
		gradedEbayColumn: "eBay",
		gradedEbayLink: "Sales",
		gradedSalesCount: "{count} sales",
		gradedSalesOne: "1 sale",
		gradedSureHigh: "sure",
		gradedSureMedium: "fairly sure",
		gradedSureLow: "unsure",
		gradedSureExplain: "How sure a price is, is the price service's own judgement: the fewer and older the sales, the less sure.",
		gradedOthersExplain: "CGC, BGS, SGC, TAG and ACE are other companies that grade cards the way PSA does.",
		gradedAllVersions: "They cover all versions of the card together, so a PSA reverse holo can be worth more than shown.",
		gradedFetchToggle: "Fetch PSA prices automatically",
		gradedLeft: "PSA lookups left today: {count} cards · more at {time}",
		gradedLeftOne: "PSA lookups left today: 1 card · more at {time}",
		gradedUsedUp: "Today's PSA lookups are used up. More come at {time}. Cards already looked up still show their prices.",
		gradedOff: "Tick the box to fetch this card's PSA prices, and those of every card you open after it. The free price service allows about 50 cards a day, so it stays off until you need it.",
		gradedLoading: "Fetching PSA prices…",
		gradedNone: "No PSA sales of this card were found.",
		gradedFailed: "The PSA prices couldn't be fetched right now. Open the card again in a minute.",

		scanBar: "Scan",
		takePhoto: "Take photo",
		cameraStarting: "Starting the camera…",
		cameraHint: "Fill the frame with the card",
		cameraAutoHint: "Fill the frame with the card: the photo takes itself",
		cameraAuto: "Take the photo by itself",
		cameraAutoShort: "Auto",
		cameraSavedHint: "Saved. Fill the frame with the next card",
		cameraHoldStill: "Hold still…",
		cameraPhotoSize: "camera {size} ({source})",
		cameraSourcePhoto: "photo",
		cameraSourceVideo: "live picture",
		cameraNoPhoto: "no full-size photo here",
		cameraPhotoFailed: "full-size photo failed",
		cameraPhotoSmall: "full-size photo only {size}",
		cameraPhotoSideways: "full-size photo {size} was on its side",
		cameraSharpened: "soft ({value}), sharpened",
		cameraSharp: "sharp ({value})",
		cameraNotAllowed: "This page isn't allowed to use the camera. Allow it in the phone's settings, or use the phone's own camera.",
		cameraFailed: "The camera couldn't start. Use the phone's own camera instead.",
		cameraUsePhone: "Use the phone's own camera",
		cameraClose: "Close the camera",
		cameraLight: "Light",
		cameraZoom: "Zoom",
		choosePhoto: "Choose photo",

		views: "Screens",
		viewScan: "Scan",
		viewCollection: "My cards",
		addToCollection: "Add to my cards",
		addAnother: "Add one more",
		saveAndNext: "Save and scan the next",
		inCollection: "You have {count} in My cards.",
		inCollectionVersion: "You have {count} of this version in My cards.",
		whichVersion: "Which version is yours?",
		versionHint: "Reverse holo: the card sparkles everywhere except the picture. Holo: the picture itself sparkles.",
		versionFromPhoto: "Reverse holo was picked because the card in the photo sparkles outside its picture. Tap another version if that's wrong.",
		storageBlocked: "This browser won't let the app save anything, so My cards can't be kept. Private browsing does this.",
		collectionEmpty: "No cards yet. Scan a card, then press “Add to my cards”.",
		kindPokemon: "Pokémon",
		kindTrainer: "Trainer cards",
		kindEnergy: "Energy cards",
		collectionSearchLabel: "Search my cards",
		collectionSearchPlaceholder: "Name, set or number",
		collectionSortLabel: "Sort by",
		sortValue: "Value",
		sortName: "Name",
		sortSet: "Set and number",
		sortNewest: "Last saved first",
		shareList: "Share list",
		shareTitle: "My Pokémon cards",
		shareHeading: "My Pokémon cards",
		shareHeadingSearch: "My Pokémon cards matching “{query}”",
		shareCopied: "The list was copied: paste it into a message or a note.",
		shareFailed: "The list couldn't be shared or copied here.",
		searchFoundOne: "1 card found",
		searchFound: "{count} cards found",
		searchWorth: "worth {price}",
		searchNothing: "No card matches “{query}”.",
		totalValue: "Total value",
		cardCountOne: "1 card",
		cardCount: "{count} cards",
		valueBasis: "Cardmarket prices (TCGplayer where Cardmarket has none)",
		notInTotal: "{count} without any price, so not in the total.",
		updatePrices: "Update prices",
		updatingPrices: "Updating prices…",
		pricesUpdated: "Prices updated.",
		refreshFailed: "The price database didn't answer. Try again in a moment.",
		noPrice: "no price",
		each: "{price} each",
		allOfThem: "{price} for all",
		oneFewer: "One fewer",
		oneMore: "One more",
		backToCollection: "Back to My cards",
		savedCardLoading: "Fetching the card's prices…",
		savedCardFailed: "The price database didn't answer, so the card's page can't be shown right now.",
		savedCardMissing: "The price database no longer has this card, so its page can't be shown.",
		tryAgain: "Try again",
		savedOnPhone: "My cards is saved on this phone only. Clearing the browser's data deletes it.",
		savedOnPhoneInstalled: "My cards is saved in this home screen app only, apart from Safari's. Sign in above to see the same cards in both.",
		collectionEmptyInstalled: "No cards here yet. The home screen app keeps its own cards, apart from Safari's: sign in above to see your account's cards.",
		installApp: "Install app",
		installTitle: "Kortpris as an app",
		installExplain: "Kortpris needs no App Store: you put it on the home screen from the browser. It then opens like an app: full screen, and at once, as its files are kept on the device.",
		installButton: "Install Kortpris",
		installYourDevice: "Your device",
		installIphoneTitle: "iPhone and iPad",
		installIphone1: "Open Kortpris in Safari.",
		installIphone2: "Tap the Share button: the square with an arrow pointing up. Can't see it? Tap ⋯ first.",
		installIphone3: "Tap “Add to Home Screen”. You may have to scroll down to find it.",
		installIphone4: "Leave “Open as Web App” on, if it is there, and tap “Add”.",
		installIphoneOther: "Chrome and Edge on an iPhone work the same way: the Share button, then “Add to Home Screen”.",
		installIphoneStorage: "On iPhone and iPad, the home screen app keeps its own saved cards, apart from Safari's. Sign in to an account (under My cards) in both to see the same cards.",
		installAndroidTitle: "Android",
		installAndroid1: "Open Kortpris in Chrome.",
		installAndroid2: "Tap the menu ⋮ at the top right.",
		installAndroid3: "Tap “Add to Home screen” or “Install app”, and then “Install”.",
		installAndroidSamsung: "Samsung Internet: tap the menu ☰ at the bottom, then “Add page to” and “Home screen”.",
		installChromebookTitle: "Chromebook",
		installOpenChrome: "Open Kortpris in Chrome.",
		installAddressIcon: "Click the install icon at the right end of the address bar: a screen with an arrow pointing down.",
		installChromebookDone: "Click “Install”. Kortpris is then with your other apps.",
		installChromeMenu: "No icon in Chrome? Open the menu ⋮, choose “Cast, save and share”, and then the install choice.",
		installComputerTitle: "Computer: Windows, Mac, Linux",
		installOpenChromeEdge: "Open Kortpris in Chrome or Edge.",
		installComputerDone: "Click “Install”. Kortpris then opens in its own window, and is with your other programs.",
		installEdgeMenu: "No icon in Edge? Open the menu ⋯, choose “Apps”, and then “Install this site as an app”.",
		installMacSafari: "Safari on a Mac: the “File” menu, then “Add to Dock”.",
		installOtherTitle: "Firefox and other browsers",
		installOtherBrowsers: "Look in the browser's menu for “Install”, “Add to Home screen” or “Add app to Home screen”. If there is none, open Kortpris in Chrome, Edge or Safari instead.",
		closeLabel: "Close",

		claudeTitle: "Read cards with Claude",
		claudeOn: "On",
		claudeOff: "Off",
		claudeExplain: "Claude reads cards far more reliably than the built-in reader: worn cards, shiny foil, and cards in other languages. It needs your own Anthropic API key, and each photo costs roughly 20–25 øre (about 3 US cents) on your Anthropic account.",
		claudeKeyLabel: "Anthropic API key",
		claudeKeyPlaceholder: "sk-ant-…",
		claudeKeyHelpBefore: "Make a key at ",
		claudeKeyHelpAfter: ". Set a monthly spending limit there too, so a mistake can never cost much.",
		claudeSave: "Save key",
		claudeRemove: "Remove key",
		claudeSaved: "Saved. New photos are read by Claude.",
		claudeRemoved: "Removed. Photos are read by the built-in reader again.",
		claudeKeyShape: "That doesn't look like an Anthropic API key. They start with “sk-ant-”.",
		claudeSaveFailed: "This browser won't let the app save the key. Private browsing does this.",
		claudePrivacy: "The key belongs to your account and is saved on this phone only: someone else signing in here doesn't get it. It is sent only to Anthropic. Photos you scan are sent to Anthropic to be read.",

		learnedTitle: "Cards the app has learned",
		learnedExplain: "When the app can't tell which card is in your photo, or picks the wrong one, and you tap or type the right one, it remembers how that card looked in your photo. So does saving the card a photo found to My cards. The next photo of that card is then recognised straight away, even when its text can't be read.",
		learnedOnPhone: "Kept on this phone only. Sign in (under My cards) to keep them in your account.",
		learnedInAccount: "Kept in {name}'s account too, so they're on every phone {name} signs in on.",
		learnedAccountFailed: "Kept on this phone for now: {name}'s account couldn't be used, because",
		learnedRulesMissing: "its online storage doesn't allow learned cards yet (the Firebase rules need updating).",
		learnedNone: "None yet.",
		learnedForget: "Forget",
		learnedForgetAll: "Forget all",
		voiceTitle: "Reading aloud",
		voiceExplain: "The voice that reads cards aloud in kids mode and on 🔊. How natural it sounds depends on the voices this phone or PC has: the most natural one is picked, but you can choose another.",
		voiceDanish: "Danish voice",
		voiceEnglish: "English voice",
		voiceTry: "Try",
		voiceAutomatic: "Automatic: {name}",
		voiceNone: "No voice on this device",
		voiceSample: "Hi! I read your Pokémon cards out loud. This Pikachu is worth about 33 kroner.",
		voiceBetterIphone: "iPhone: Settings → Accessibility → Read & Speak (on older iPhones: Spoken Content) → Voices → Danish → Sara, then download “Sara (Enhanced)”. English works the same way. Then choose it here.",
		voiceBetterAndroid: "Android: in Settings → Google Text-to-speech you can install the Danish and English voices.",
		voiceBetterPc: "PC: Chrome has natural Google voices for English, but only an old one for Danish. Microsoft Edge has natural Danish voices (Christel and Jeppe).",
		claudeReading: "Claude is reading the card…",
		claudeNotACard: "Claude doesn't see a Pokémon card in this photo. Try again with the whole card in view.",
		claudeKeyWrong: "Claude didn't accept your API key, so the built-in reader was used. Check the key under “Read cards with Claude”.",
		claudeNoCredit: "Your Anthropic account is out of credit, so the built-in reader was used.",
		claudeBusy: "Claude is busy right now, so the built-in reader was used.",
		claudeFailed: "Claude couldn't read this photo, so the built-in reader was used.",

		accountTitle: "Your account",
		accountExplain: "Sign in to keep your cards in an account and see them on any phone. Everyone in the family can have their own.",
		accountModes: "Sign in or create an account",
		signIn: "Sign in",
		createAccount: "Create account",
		signingIn: "Signing in…",
		creatingAccount: "Creating account…",
		usernameLabel: "Username",
		usernameHint: "3–20 characters: letters a–z, numbers, - and _. Don't use your full name.",
		passwordLabel: "Password",
		passwordAgainLabel: "Password again",
		showPassword: "Show",
		hidePassword: "Hide",
		passwordTip: "Tip: three or four random words are strong and easy to remember, like “purple tiger eats rockets”.",
		passwordTooShort: "At least {min} characters. {left} to go.",
		passwordHasUsername: "Don't put your username in the password.",
		passwordTooSimple: "Too easy to guess. Try three or four random words instead.",
		passwordStrong: "Strong password.",
		passwordCheckerLoading: "Checking the password…",
		passwordCheckerFailed: "The password checker couldn't be downloaded. Check the internet connection.",
		passwordsDiffer: "The two passwords aren't the same.",
		usernameInvalid: "Usernames are 3–20 characters: letters a–z, numbers, - and _.",
		needPassword: "Type your password.",
		accountCreated: "Account created. Welcome, {name}!",
		signedInAs: "Signed in as",
		signOut: "Sign out",
		phoneCardsOne: "This phone has 1 card saved outside any account.",
		phoneCards: "This phone has {count} cards saved outside any account.",
		moveCards: "Move them into this account",
		cardsMoved: "Moved. They're in your account now.",
		loadingAccountCards: "Loading your cards…",
		savedInAccount: "These cards are saved in {name}'s account and show up on every phone {name} signs in on.",
		notSaved: "Not saved to the account.",
		usernameTaken: "That username is taken. Pick another one.",
		wrongLogin: "Wrong username or password.",
		tooManyTries: "Too many tries. Wait a few minutes, then try again.",
		passwordRejected: "That password is too simple.",
		signUpClosed: "New accounts are switched off. Ask the grown-up who set up Kortpris.",
		accountsNotSetUp: "Accounts aren't switched on in Firebase yet. Finish SETUP-ACCOUNTS.md (steps 3 to 6).",
		noConnection: "No internet connection. Try again when you're online.",
		permissionDenied: "This account isn't allowed to open these cards.",
		accountFailed: "Something went wrong ({code}). Try again.",
		accountsOffline: "Accounts can't load right now. Your cards on this phone still work.",

		// Kids mode: big pictures, few words, and the phone reads out loud.
		kidsMode: "Kids",
		kidsModeLabel: "Kids mode: big buttons, and the phone reads out loud",
		readAloud: "Read aloud",
		kidIdle: "Take a photo of your card",
		kidBusy: "One moment…",
		kidFound: "Found it!",
		kidPickOne: "Which card is yours? Tap it.",
		kidNotFound: "Couldn't find the card. Try a new photo.",
		kidTryLater: "Try again in a moment.",
		kidPriceAbout: "about {price}",
		kidPriceUnder: "under {price}",
		kidSave: "Save card",
		kidSaveAnother: "Save one more",
		kidSaveAndNext: "Save, then the next card",
		kidHave: "You have {count}",
		balls: "{count} of 5: {ball}",
		ball_poke: "a Poké Ball",
		ball_premier: "Premier Balls",
		ball_great: "Great Balls",
		ball_ultra: "Ultra Balls",
		ball_master: "Master Balls",
		sayKidsModeOn: "Kids mode is on. Press the yellow button and take a photo of your card.",
		sayTakePhoto: "Take a photo of the whole card.",
		sayChoosePhoto: "Choose a photo of your card.",
		sayLooking: "One moment. I'm looking at the card.",
		sayPickOne: "Which card is yours? Tap it.",
		sayNotFound: "I couldn't find the card. Take a new photo with the whole card in it.",
		sayTryLater: "The price list isn't answering. Try again in a moment.",
		sayWorth: "{name}. It's worth {price}.",
		sayWorthVersion: "{name}, {version}. It's worth {price}.",
		sayWow: "Wow! {sentence}",
		sayNoPrice: "{name}. I don't know what it's worth.",
		saySaved: "Saved in My cards!",
		sayCollection: "Your cards are worth {price} in all.",
		sayCollectionEmpty: "You have no cards yet.",
		spokenAbout: "about {amount}",
		spokenUnder: "less than {amount}",
		unitOneDKK: "krone",
		unitManyDKK: "kroner",
		unitOneEUR: "euro",
		unitManyEUR: "euros",
		unitOneGBP: "pound",
		unitManyGBP: "pounds",
		unitOneIDR: "rupiah",
		unitManyIDR: "rupiah",
	},

	da: {
		tagline: "Fotografér et Pokémon-kort. Se hvad det sælges for.",
		languageSwitch: "Sprog",
		howItWorks: "Sådan virker det",
		step1Verb: "Fotografér",
		step1Rest: " hele kortet lige forfra i godt lys.",
		step2Verb: "Tjek",
		step2Rest: " navn og nummer, og tryk på dit kort.",
		step3Verb: "Se",
		step3Rest: " de seneste priser fra Cardmarket og TCGplayer.",
		tryExample: "Prøv med et eksempelkort",

		yourCard: "Dit kort",
		yourPhoto: "Dit billede",
		nameLabel: "Navn på kortet",
		namePlaceholder: "f.eks. Charizard",
		numberLabel: "Nummer i hjørnet forneden",
		numberPlaceholder: "f.eks. 4/102",
		search: "Søg",

		statusIdle: "Tag et billede, eller skriv navn og nummer fra kortet.",
		downloadingExample: "Henter eksempelkortet…",
		exampleFailed: "Kunne ikke hente eksempelkortet. Tjek internetforbindelsen.",
		readerStarting: "Gør tekstlæseren klar…",
		readerStartingSlow: "Gør tekstlæseren klar (tager lidt tid første gang)…",
		reading: "Læser kortet…",
		readFailed: "Kunne ikke læse kortet. Skriv navn og nummer herunder, eller prøv et skarpere billede i bedre lys.",
		unsureName: "Usikker på, hvad kortet hedder. Tjek navnet, skriv nummeret fra hjørnet forneden (fx 86/110), og tryk så på Søg. Glimtende kort er svære at læse.",
		typeNumber: "{total} kort hedder »{name}«; dem, der ligner dit billede mest, står først. Skriv nummeret fra hjørnet forneden (fx 86/110), og tryk på Søg for at være sikker.",
		numberNotFound: "Intet »{name}«-kort har nummeret {number}. Tjek nummeret i hjørnet forneden, og tryk på Søg igen.",
		needNameOrNumber: "Skriv kortets navn eller nummer for at søge.",
		lookingUp: "Slår priser op…",
		foundOne: "Fundet!",
		foundMany: "Fandt {count} mulige kort. Tryk på dit.",
		comparingPictures: "Sammenligner billeder…",
		comparingProgress: "Sammenligner billeder… {done} af {total}",
		foundManyByLook: "Fandt {count} mulige kort, det mest lignende først. Tryk på dit.",
		bestMatchOpened: "Det ligner dit kort. Forkert? Tryk på det rigtige herunder.",
		learnedOpened: "Genkendt: det kort har du vist mig før. Forkert? Skriv det rigtige navn og nummer, og tryk på Søg.",
		learnedChecking: "Genkendt: det kort har du vist mig før. Tjekker teksten på det…",
		learnedOtherPrint: "Navnet og nummeret på kortet hører til et andet tryk af samme billede, så det vises, ikke det kort, du viste mig før.",
		learnedSuggested: "Kunne ikke læse kortet, men det ligner lidt kort, du har vist mig før. Er dit kort herunder, så tryk på det. Ellers skriv navn og nummer.",
		bestMatch: "Bedste match",
		seenBefore: "Set før",
		noMatch: "Ingen kort passede. Sammenlign navn og nummer med kortet, og søg igen.",
		apiDown: "Prisdatabasen svarede ikke. Vent lidt, og tryk så på Søg.",
		apiTooMany: "Prisdatabasen har fået for mange opslag fra denne internetforbindelse i dag. Prøv igen senere, eller brug mobildata.",

		resultsTitle: "Hvilket er dit?",
		matchExact: "Kort med navnet »{name}« og nummer {number}.",
		matchAnySet: "Kort med navnet »{name}« og nummer {number}, fra alle sæt.",
		matchNameTotal: "Kort med navnet »{name}« fra et sæt med {total} kort. Tjek nummeret.",
		matchByLook: "Navn og nummer kunne ikke begge læses, så her er kortene, der passer med en del af det, det mest lignende først.",
		matchSetSizeLook: "Kun sættets størrelse kunne læses, så her er kortene fra sæt med {total} kort, det mest lignende først.",
		matchLearned: "Genkendt fra et tidligere billede.",
		matchLearnedSuggested: "Kort, du har vist mig før, som ligner billedet lidt, det mest lignende først.",
		matchNumberNameMissed: "Intet kort med navnet »{name}« har nummer {number}, så her er alle kort med det nummer. Tjek navnet.",
		matchNumberOnly: "Alle kort med nummer {number}.",
		matchNameOnly: "Alle »{name}«-kort, nyeste først. Tilføj nummeret fra hjørnet forneden for at indsnævre søgningen.",
		matchNumberNoTotal: "Kort med nummer {number}, nyeste først. Tilføj navnet for at indsnævre søgningen.",
		showingFirst: " Viser de første {count}.",

		noPrices: "Ingen har solgt kortet på Cardmarket eller TCGplayer for nylig, så der er ingen pris endnu.",
		pricesFailed: "Prisdatabasen svarede ikke, så priserne kan ikke vises lige nu. Søg igen om lidt.",
		soldOnEbay: "Se, hvad det er solgt for på eBay",
		notYours: "Ikke dit kort? Ret navn eller nummer ovenfor, og tryk på Søg.",
		ungraded: "Priserne gælder ugraderede kort. Et ridset, bøjet eller falmet kort sælges for mindre.",
		pricesFrom: "Priser fra {date}",
		weeksOld: "{count} uger gamle",
		monthsOld: "{count} måneder gamle",

		cardmarketStat: "Cardmarket · Europa",
		cardmarketPrice: "Pris",
		euro: "Euro",
		kroner: "Kroner",
		avg30: "Gennemsnit, 30 dage",
		avg7: "Gennemsnit, 7 dage",
		trendPrice: "Trend",
		averageSellPrice: "Gennemsnitligt salg",
		lowPrice: "Billigste udbud",
		reverseHoloAvg30: "Reverse holo, gennemsnit 30 dage",
		reverseHoloTrend: "Reverse holo, trend",
		openCardmarket: "Åbn på Cardmarket",

		tcgplayerStat: "TCGplayer · USA",
		tcgplayerVersion: "Version",
		tcgplayerMarket: "Marked",
		tcgplayerLowest: "Laveste",
		marketPrice: "markedspris",
		holofoil: "Holo",
		normal: "Normal",
		reverseHolofoil: "Reverse holo",
		firstEditionHolofoil: "1. udgave, holo",
		firstEditionNormal: "1. udgave",
		unlimitedHolofoil: "Unlimited, holo",
		unlimited: "Unlimited",
		openTcgplayer: "Åbn på TCGplayer",

		footerBefore: "Kortdata og priser kommer fra den gratis kortdatabase ",
		footerLink: "TCGdex",
		footerAfter: ". Ikke lavet af eller tilknyttet Pokémon, Cardmarket eller TCGplayer.",
		appVersion: "Kortpris version {version}",
		currencyLabel: "Valuta",
		ratesFrom: "Valutakurser fra {date} (Den Europæiske Centralbank).",
		ratesMissing: "Valutakurserne kunne ikke hentes, så priserne vises i euro indtil videre.",
		gradedTitle: "Graderede kort (PSA)",
		gradedExplain: "PSA bedømmer et korts stand fra 1 til 10 og forsegler det i et etui. Et PSA 10 kan sælges for mange gange priserne ovenfor. Linkene viser, hvad graderede eksemplarer af kortet faktisk er solgt for.",
		gradedEbay: "{grade}-salg på eBay",
		gradedPriceCharting: "Alle karakterer på PriceCharting",
		gradedGrade: "Karakter",
		gradedPrice: "Pris",
		gradedDollars: "I dollar",
		gradedSales: "Salg",
		gradedFrom: "Hver karakters pris ud fra kortets eBay-salg, beregnet af PokemonPriceTracker: de seneste salg tæller mest, og mærkelige salg er sorteret fra. Jo færre salg, jo mere usikker er prisen.",
		gradedMore: "Seneste salg, andre firmaer og eBay",
		gradedLastSale: "Seneste salg",
		gradedEbayColumn: "eBay",
		gradedEbayLink: "Salg",
		gradedSalesCount: "{count} salg",
		gradedSalesOne: "1 salg",
		gradedSureHigh: "sikker",
		gradedSureMedium: "ret sikker",
		gradedSureLow: "usikker",
		gradedSureExplain: "Hvor sikker en pris er, vurderer pristjenesten selv: jo færre og ældre salg, jo mindre sikker.",
		gradedOthersExplain: "CGC, BGS, SGC, TAG og ACE er andre firmaer, der graderer kort ligesom PSA.",
		gradedAllVersions: "Salgene gælder alle kortets versioner under ét, så et PSA-gradet reverse holo kan være mere værd end vist.",
		gradedFetchToggle: "Hent PSA-priser automatisk",
		gradedLeft: "PSA-opslag tilbage i dag: {count} kort · nye kl. {time}",
		gradedLeftOne: "PSA-opslag tilbage i dag: 1 kort · nye kl. {time}",
		gradedUsedUp: "Dagens PSA-opslag er brugt op. Der kommer nye kl. {time}. Kort, der allerede er slået op, viser stadig deres priser.",
		gradedOff: "Sæt flueben for at hente kortets PSA-priser og priserne på alle kort, du åbner bagefter. Den gratis pristjeneste giver cirka 50 kort om dagen, så det er slået fra, til du har brug for det.",
		gradedLoading: "Henter PSA-priser …",
		gradedNone: "Der blev ikke fundet PSA-salg af kortet.",
		gradedFailed: "PSA-priserne kunne ikke hentes lige nu. Åbn kortet igen om et minut.",

		scanBar: "Scan",
		takePhoto: "Tag billede",
		cameraStarting: "Starter kameraet …",
		cameraHint: "Fyld rammen ud med kortet",
		cameraAutoHint: "Fyld rammen ud med kortet: billedet tager sig selv",
		cameraAuto: "Tag billedet af sig selv",
		cameraAutoShort: "Auto",
		cameraSavedHint: "Gemt. Fyld rammen ud med det næste kort",
		cameraHoldStill: "Hold stille …",
		cameraPhotoSize: "kamera {size} ({source})",
		cameraSourcePhoto: "foto",
		cameraSourceVideo: "livebillede",
		cameraNoPhoto: "intet fuldt foto her",
		cameraPhotoFailed: "fuldt foto fejlede",
		cameraPhotoSmall: "fuldt foto kun {size}",
		cameraPhotoSideways: "fuldt foto {size} lå på siden",
		cameraSharpened: "blødt ({value}), gjort skarpere",
		cameraSharp: "skarpt ({value})",
		cameraNotAllowed: "Siden må ikke bruge kameraet. Giv lov i telefonens indstillinger, eller brug telefonens eget kamera.",
		cameraFailed: "Kameraet kunne ikke starte. Brug telefonens eget kamera i stedet.",
		cameraUsePhone: "Brug telefonens eget kamera",
		cameraClose: "Luk kameraet",
		cameraLight: "Lys",
		cameraZoom: "Zoom",
		choosePhoto: "Vælg billede",

		views: "Skærme",
		viewScan: "Scan",
		viewCollection: "Mine kort",
		addToCollection: "Læg i Mine kort",
		addAnother: "Læg én mere i",
		saveAndNext: "Gem og scan det næste",
		inCollection: "Du har {count} i Mine kort.",
		inCollectionVersion: "Du har {count} af denne version i Mine kort.",
		whichVersion: "Hvilken version har du?",
		versionHint: "Reverse holo: kortet glimter overalt undtagen på billedet. Holo: selve billedet glimter.",
		versionFromPhoto: "Reverse holo er valgt, fordi kortet på billedet glimter uden for sit billede. Tryk på en anden version, hvis det er forkert.",
		storageBlocked: "Browseren tillader ikke, at appen gemmer noget, så Mine kort kan ikke gemmes. Privat browsing gør det.",
		collectionEmpty: "Ingen kort endnu. Scan et kort, og tryk så på »Læg i Mine kort«.",
		kindPokemon: "Pokémon",
		kindTrainer: "Trainerkort",
		kindEnergy: "Energikort",
		collectionSearchLabel: "Søg i mine kort",
		collectionSearchPlaceholder: "Navn, sæt eller nummer",
		collectionSortLabel: "Sortér efter",
		sortValue: "Værdi",
		sortName: "Navn",
		sortSet: "Sæt og nummer",
		sortNewest: "Senest gemt først",
		shareList: "Del listen",
		shareTitle: "Mine Pokémon-kort",
		shareHeading: "Mine Pokémon-kort",
		shareHeadingSearch: "Mine Pokémon-kort, der passer med »{query}«",
		shareCopied: "Listen er kopieret: sæt den ind i en besked eller en note.",
		shareFailed: "Listen kunne ikke deles eller kopieres her.",
		searchFoundOne: "1 kort fundet",
		searchFound: "{count} kort fundet",
		searchWorth: "værd {price}",
		searchNothing: "Intet kort passer med »{query}«.",
		totalValue: "Samlet værdi",
		cardCountOne: "1 kort",
		cardCount: "{count} kort",
		valueBasis: "Cardmarket-priser (TCGplayer, hvor Cardmarket ingen har)",
		notInTotal: "{count} uden nogen pris, så de er ikke med i summen.",
		updatePrices: "Opdater priser",
		updatingPrices: "Opdaterer priser…",
		pricesUpdated: "Priserne er opdateret.",
		refreshFailed: "Prisdatabasen svarede ikke. Prøv igen om lidt.",
		noPrice: "ingen pris",
		each: "{price} pr. stk.",
		allOfThem: "{price} for alle",
		oneFewer: "Én mindre",
		oneMore: "Én mere",
		backToCollection: "Tilbage til Mine kort",
		savedCardLoading: "Henter kortets priser…",
		savedCardFailed: "Prisdatabasen svarede ikke, så kortets side kan ikke vises lige nu.",
		savedCardMissing: "Prisdatabasen har ikke dette kort længere, så dets side kan ikke vises.",
		tryAgain: "Prøv igen",
		savedOnPhone: "Mine kort gemmes kun på denne telefon. Hvis browserens data slettes, forsvinder de.",
		savedOnPhoneInstalled: "Mine kort gemmes kun i denne app på hjemmeskærmen, adskilt fra Safari. Log ind ovenfor for at se de samme kort begge steder.",
		collectionEmptyInstalled: "Ingen kort her endnu. Appen på hjemmeskærmen gemmer sine egne kort, adskilt fra Safari: log ind ovenfor for at se din kontos kort.",
		installApp: "Installer app",
		installTitle: "Kortpris som app",
		installExplain: "Kortpris skal ikke hentes i App Store: du lægger den på hjemmeskærmen fra browseren. Så åbner den som en app: i fuld skærm og med det samme, for dens filer gemmes på enheden.",
		installButton: "Installer Kortpris",
		installYourDevice: "Din enhed",
		installIphoneTitle: "iPhone og iPad",
		installIphone1: "Åbn Kortpris i Safari.",
		installIphone2: "Tryk på Del-knappen: firkanten med en pil op. Kan du ikke se den, så tryk først på ⋯.",
		installIphone3: "Tryk på »Føj til hjemmeskærm«. Du skal måske rulle ned for at finde den.",
		installIphone4: "Lad »Åbn som webapp« være slået til, hvis den er der, og tryk på »Tilføj«.",
		installIphoneOther: "Chrome og Edge på iPhone virker på samme måde: Del-knappen og så »Føj til hjemmeskærm«.",
		installIphoneStorage: "På iPhone og iPad gemmer appen på hjemmeskærmen sine egne kort, adskilt fra Safari. Log ind på en konto (under Mine kort) begge steder for at se de samme kort.",
		installAndroidTitle: "Android",
		installAndroid1: "Åbn Kortpris i Chrome.",
		installAndroid2: "Tryk på menuen ⋮ øverst til højre.",
		installAndroid3: "Tryk på »Føj til startskærm« eller »Installer app«, og så på »Installer«.",
		installAndroidSamsung: "Samsung Internet: tryk på menuen ☰ nederst, så »Tilføj side til« og »Startskærm«.",
		installChromebookTitle: "Chromebook",
		installOpenChrome: "Åbn Kortpris i Chrome.",
		installAddressIcon: "Klik på installer-ikonet yderst til højre i adresselinjen: en skærm med en pil ned.",
		installChromebookDone: "Klik på »Installer«. Kortpris ligger så blandt dine andre apps.",
		installChromeMenu: "Intet ikon i Chrome? Åbn menuen ⋮, vælg »Cast, gem og del«, og så installer-valget.",
		installComputerTitle: "Computer: Windows, Mac, Linux",
		installOpenChromeEdge: "Åbn Kortpris i Chrome eller Edge.",
		installComputerDone: "Klik på »Installer«. Kortpris åbner så i sit eget vindue og ligger blandt dine andre programmer.",
		installEdgeMenu: "Intet ikon i Edge? Åbn menuen ⋯, vælg »Apps«, og så »Installer dette websted som en app«.",
		installMacSafari: "Safari på en Mac: menuen »Arkiv« og så »Føj til Dock«.",
		installOtherTitle: "Firefox og andre browsere",
		installOtherBrowsers: "Kig i browserens menu efter »Installer«, »Føj til startskærm« eller »Føj app til startskærm«. Er der ingen, så åbn Kortpris i Chrome, Edge eller Safari i stedet.",
		closeLabel: "Luk",

		claudeTitle: "Læs kort med Claude",
		claudeOn: "Til",
		claudeOff: "Fra",
		claudeExplain: "Claude læser kort langt mere pålideligt end den indbyggede læser: slidte kort, blankt folie og kort på andre sprog. Det kræver din egen Anthropic API-nøgle, og hvert billede koster cirka 20–25 øre på din Anthropic-konto.",
		claudeKeyLabel: "Anthropic API-nøgle",
		claudeKeyPlaceholder: "sk-ant-…",
		claudeKeyHelpBefore: "Lav en nøgle på ",
		claudeKeyHelpAfter: ". Sæt også en månedlig beløbsgrænse dér, så en fejl aldrig kan blive dyr.",
		claudeSave: "Gem nøgle",
		claudeRemove: "Fjern nøgle",
		claudeSaved: "Gemt. Nye billeder læses af Claude.",
		claudeRemoved: "Fjernet. Billeder læses igen af den indbyggede læser.",
		claudeKeyShape: "Det ligner ikke en Anthropic API-nøgle. De starter med »sk-ant-«.",
		claudeSaveFailed: "Browseren tillader ikke, at appen gemmer nøglen. Privat browsing gør det.",
		claudePrivacy: "Nøglen hører til din konto og gemmes kun på denne telefon: en anden, der logger ind her, får den ikke. Den sendes kun til Anthropic. Billeder, du scanner, sendes til Anthropic for at blive læst.",

		learnedTitle: "Kort, appen har lært",
		learnedExplain: "Når appen ikke kan se, hvilket kort der er på dit billede, eller vælger det forkerte, og du trykker på eller skriver det rigtige, husker den, hvordan kortet så ud på dit billede. Det gør den også, når du gemmer det fundne kort i Mine kort. Næste billede af det kort bliver så genkendt med det samme, også når teksten ikke kan læses.",
		learnedOnPhone: "Gemmes kun på denne telefon. Log ind (under Mine kort) for at gemme dem på din konto.",
		learnedInAccount: "Gemmes også på kontoen »{name}«, så de er med på alle telefoner, hvor {name} logger ind.",
		learnedAccountFailed: "Gemmes på denne telefon indtil videre: kontoen »{name}« kunne ikke bruges, fordi",
		learnedRulesMissing: "dens lager på nettet tillader ikke lærte kort endnu (Firebase-reglerne skal opdateres).",
		learnedNone: "Ingen endnu.",
		learnedForget: "Glem",
		learnedForgetAll: "Glem alle",
		voiceTitle: "Oplæsning",
		voiceExplain: "Stemmen, der læser kortene op i børnetilstand og på 🔊. Hvor naturlig den lyder, afhænger af de stemmer, telefonen eller pc'en har: den mest naturlige vælges, men du kan vælge en anden.",
		voiceDanish: "Dansk stemme",
		voiceEnglish: "Engelsk stemme",
		voiceTry: "Prøv",
		voiceAutomatic: "Automatisk: {name}",
		voiceNone: "Ingen stemme på denne enhed",
		voiceSample: "Hej! Jeg læser dine Pokémon-kort højt. Den her Pikachu er cirka 33 kroner værd.",
		voiceBetterIphone: "iPhone: Indstillinger → Tilgængelighed → »Read & Speak« (på en dansk iPhone »Læs og tal«, på ældre »Oplæst indhold«) → Stemmer → Dansk → Sara, og hent så »Sara (Forbedret)«. Engelsk på samme måde. Vælg den så her.",
		voiceBetterAndroid: "Android: under Indstillinger → Google Tekst-til-tale kan du installere de danske og engelske stemmer.",
		voiceBetterPc: "Pc: Chrome har naturlige Google-stemmer på engelsk, men kun en gammel på dansk. Microsoft Edge har naturlige danske stemmer (Christel og Jeppe).",
		claudeReading: "Claude læser kortet…",
		claudeNotACard: "Claude kan ikke se et Pokémon-kort på billedet. Prøv igen med hele kortet i billedet.",
		claudeKeyWrong: "Claude accepterede ikke din API-nøgle, så den indbyggede læser blev brugt. Tjek nøglen under »Læs kort med Claude«.",
		claudeNoCredit: "Din Anthropic-konto har ikke mere kredit, så den indbyggede læser blev brugt.",
		claudeBusy: "Claude har travlt lige nu, så den indbyggede læser blev brugt.",
		claudeFailed: "Claude kunne ikke læse billedet, så den indbyggede læser blev brugt.",

		accountTitle: "Din konto",
		accountExplain: "Log ind for at gemme dine kort på en konto og se dem på enhver telefon. Alle i familien kan have deres egen.",
		accountModes: "Log ind eller opret en konto",
		signIn: "Log ind",
		createAccount: "Opret konto",
		signingIn: "Logger ind…",
		creatingAccount: "Opretter konto…",
		usernameLabel: "Brugernavn",
		usernameHint: "3–20 tegn: bogstaverne a–z, tal, - og _. Brug ikke dit fulde navn.",
		passwordLabel: "Adgangskode",
		passwordAgainLabel: "Adgangskode igen",
		showPassword: "Vis",
		hidePassword: "Skjul",
		passwordTip: "Tip: tre-fire tilfældige ord er stærke og lette at huske, fx »lilla tiger spiser raketter«.",
		passwordTooShort: "Mindst {min} tegn. {left} mere.",
		passwordHasUsername: "Brug ikke dit brugernavn i adgangskoden.",
		passwordTooSimple: "For let at gætte. Prøv tre-fire tilfældige ord i stedet.",
		passwordStrong: "Stærk adgangskode.",
		passwordCheckerLoading: "Tjekker adgangskoden…",
		passwordCheckerFailed: "Adgangskode-tjekket kunne ikke hentes. Tjek internetforbindelsen.",
		passwordsDiffer: "De to adgangskoder er ikke ens.",
		usernameInvalid: "Brugernavne er 3–20 tegn: bogstaverne a–z, tal, - og _.",
		needPassword: "Skriv din adgangskode.",
		accountCreated: "Kontoen er oprettet. Velkommen, {name}!",
		signedInAs: "Logget ind som",
		signOut: "Log ud",
		phoneCardsOne: "Denne telefon har 1 kort gemt uden for en konto.",
		phoneCards: "Denne telefon har {count} kort gemt uden for en konto.",
		moveCards: "Flyt dem ind på denne konto",
		cardsMoved: "Flyttet. De ligger nu på din konto.",
		loadingAccountCards: "Henter dine kort…",
		savedInAccount: "Kortene er gemt på kontoen »{name}« og vises på alle telefoner, hvor {name} logger ind.",
		notSaved: "Ikke gemt på kontoen.",
		usernameTaken: "Det brugernavn er taget. Vælg et andet.",
		wrongLogin: "Forkert brugernavn eller adgangskode.",
		tooManyTries: "For mange forsøg. Vent et par minutter, og prøv igen.",
		passwordRejected: "Adgangskoden er for simpel.",
		signUpClosed: "Nye konti er slået fra. Spørg den voksne, der har sat Kortpris op.",
		accountsNotSetUp: "Konti er ikke slået til i Firebase endnu. Gør SETUP-ACCOUNTS.md færdig (trin 3 til 6).",
		noConnection: "Ingen internetforbindelse. Prøv igen, når du er online.",
		permissionDenied: "Denne konto må ikke åbne disse kort.",
		accountFailed: "Noget gik galt ({code}). Prøv igen.",
		accountsOffline: "Konti kan ikke indlæses lige nu. Kortene på denne telefon virker stadig.",

		// Børnetilstand: store billeder, få ord, og telefonen læser højt.
		kidsMode: "Børn",
		kidsModeLabel: "Børnetilstand: store knapper, og telefonen læser højt",
		readAloud: "Læs højt",
		kidIdle: "Tag et billede af dit kort",
		kidBusy: "Et øjeblik…",
		kidFound: "Fundet!",
		kidPickOne: "Hvilket kort er dit? Tryk på det.",
		kidNotFound: "Kunne ikke finde kortet. Prøv et nyt billede.",
		kidTryLater: "Prøv igen om lidt.",
		kidPriceAbout: "cirka {price}",
		kidPriceUnder: "under {price}",
		kidSave: "Gem kortet",
		kidSaveAnother: "Gem ét mere",
		kidSaveAndNext: "Gem, og tag det næste kort",
		kidHave: "Du har {count}",
		balls: "{count} af 5: {ball}",
		ball_poke: "en Poké Ball",
		ball_premier: "Premier Balls",
		ball_great: "Great Balls",
		ball_ultra: "Ultra Balls",
		ball_master: "Master Balls",
		sayKidsModeOn: "Børnetilstand er slået til. Tryk på den gule knap, og tag et billede af dit kort.",
		sayTakePhoto: "Tag et billede af hele kortet.",
		sayChoosePhoto: "Vælg et billede af dit kort.",
		sayLooking: "Et øjeblik. Jeg kigger på kortet.",
		sayPickOne: "Hvilket kort er dit? Tryk på det.",
		sayNotFound: "Jeg kunne ikke finde kortet. Tag et nyt billede, hvor hele kortet er med.",
		sayTryLater: "Prislisten svarer ikke. Prøv igen om lidt.",
		sayWorth: "{name}. Det er {price} værd.",
		sayWorthVersion: "{name}, {version}. Det er {price} værd.",
		sayWow: "Wow! {sentence}",
		sayNoPrice: "{name}. Jeg ved ikke, hvad det er værd.",
		saySaved: "Gemt i Mine kort!",
		sayCollection: "Dine kort er {price} værd i alt.",
		sayCollectionEmpty: "Du har ingen kort endnu.",
		spokenAbout: "cirka {amount}",
		spokenUnder: "under {amount}",
		unitOneDKK: "krone",
		unitManyDKK: "kroner",
		unitOneEUR: "euro",
		unitManyEUR: "euro",
		unitOneGBP: "pund",
		unitManyGBP: "pund",
		unitOneIDR: "rupiah",
		unitManyIDR: "rupiah",
	},
};

// Numbers, money and dates are written the way each language expects:
// "18.114,21 kr." in Danish, "DKK 18,114.21" in English.
const NUMBER_LOCALES = {
	en: "en-GB",
	da: "da-DK",
};
